// Package ileapv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package ileapv1

import (
	"encoding/json"
	"time"
)

// Defines values for AccessDeniedCode.
const (
	AccessDeniedCodeAccessDenied AccessDeniedCode = "AccessDenied"
)

// Defines values for AssuranceBoundary.
const (
	CradleToGate AssuranceBoundary = "Cradle-to-Gate"
	GateToGate   AssuranceBoundary = "Gate-to-Gate"
)

// Defines values for AssuranceCoverage.
const (
	CorporateLevel AssuranceCoverage = "corporate level"
	PCFSystem      AssuranceCoverage = "PCF system"
	ProductLevel   AssuranceCoverage = "product level"
	ProductLine    AssuranceCoverage = "product line"
)

// Defines values for AssuranceLevel.
const (
	Limited    AssuranceLevel = "limited"
	Reasonable AssuranceLevel = "reasonable"
)

// Defines values for BadRequestCode.
const (
	BadRequestCodeBadRequest BadRequestCode = "BadRequest"
)

// Defines values for BiogenicAccountingMethodology.
const (
	GHGP    BiogenicAccountingMethodology = "GHGP"
	ISO     BiogenicAccountingMethodology = "ISO"
	PEF     BiogenicAccountingMethodology = "PEF"
	Quantis BiogenicAccountingMethodology = "Quantis"
)

// Defines values for CharacterizationFactors.
const (
	AR5 CharacterizationFactors = "AR5"
	AR6 CharacterizationFactors = "AR6"
)

// Defines values for CrossSectoralStandard.
const (
	GHGProtocolProductStandard CrossSectoralStandard = "GHG Protocol Product standard"
	ISOStandard14044           CrossSectoralStandard = "ISO Standard 14044"
	ISOStandard14067           CrossSectoralStandard = "ISO Standard 14067"
)

// Defines values for DeclaredUnit.
const (
	CubicMeter   DeclaredUnit = "cubic meter"
	Kilogram     DeclaredUnit = "kilogram"
	KilowattHour DeclaredUnit = "kilowatt hour"
	Liter        DeclaredUnit = "liter"
	Megajoule    DeclaredUnit = "megajoule"
	SquareMeter  DeclaredUnit = "square meter"
	TonKilometer DeclaredUnit = "ton kilometer"
)

// Defines values for EnergyCarrierType.
const (
	AviationFuel EnergyCarrierType = "Aviation fuel"
	CNG          EnergyCarrierType = "CNG"
	Diesel       EnergyCarrierType = "Diesel"
	Electric     EnergyCarrierType = "Electric"
	HFO          EnergyCarrierType = "HFO"
	HVO          EnergyCarrierType = "HVO"
	Hydrogen     EnergyCarrierType = "Hydrogen"
	LNG          EnergyCarrierType = "LNG"
	LPG          EnergyCarrierType = "LPG"
	MGO          EnergyCarrierType = "MGO"
	Methanol     EnergyCarrierType = "Methanol"
	Petrol       EnergyCarrierType = "Petrol"
)

// Defines values for EnergyConsumptionUnit.
const (
	KWh EnergyConsumptionUnit = "kWh"
	Kg  EnergyConsumptionUnit = "kg"
	L   EnergyConsumptionUnit = "l"
	MJ  EnergyConsumptionUnit = "MJ"
)

// Defines values for FeedstockType.
const (
	CookingOil           FeedstockType = "Cooking oil"
	Fossil               FeedstockType = "Fossil"
	Grid                 FeedstockType = "Grid"
	NaturalGas           FeedstockType = "Natural gas"
	RenewableElectricity FeedstockType = "Renewable electricity"
)

// Defines values for NoSuchFootprintCode.
const (
	NoSuchFootprintCodeNoSuchFootprint NoSuchFootprintCode = "NoSuchFootprint"
)

// Defines values for NotImplementedCode.
const (
	NotImplementedCodeNotImplemented NotImplementedCode = "NotImplemented"
)

// Defines values for PackagingOrTrEqType.
const (
	Box          PackagingOrTrEqType = "Box"
	Container    PackagingOrTrEqType = "Container"
	ContainerFEU PackagingOrTrEqType = "Container-FEU"
	ContainerTEU PackagingOrTrEqType = "Container-TEU"
	Pallet       PackagingOrTrEqType = "Pallet"
)

// Defines values for PathfinderRequestEventType.
const (
	PathfinderRequestEventTypeCreatedV1 PathfinderRequestEventType = "org.wbcsd.pathfinder.ProductFootprintRequest.Created.v1"
)

// Defines values for PathfinderUpdateEventType.
const (
	PathfinderUpdateEventTypePublishedV1 PathfinderUpdateEventType = "org.wbcsd.pathfinder.ProductFootprint.Published.v1"
)

// Defines values for PfStatus.
const (
	Active     PfStatus = "Active"
	Deprecated PfStatus = "Deprecated"
)

// Defines values for ProductOrSectorSpecificRuleOperator.
const (
	EPDInternational         ProductOrSectorSpecificRuleOperator = "EPD International"
	ProductRuleOperatorOther ProductOrSectorSpecificRuleOperator = "Other"
	ProductRulePEF           ProductOrSectorSpecificRuleOperator = "PEF"
)

// Defines values for TadTempControl.
const (
	Ambient      TadTempControl = "ambient"
	Refrigerated TadTempControl = "refrigerated"
)

// Defines values for TransportMode.
const (
	Air            TransportMode = "Air"
	InlandWaterway TransportMode = "InlandWaterway"
	Rail           TransportMode = "Rail"
	Road           TransportMode = "Road"
	Sea            TransportMode = "Sea"
)

// Defines values for UNRegionOrSubregion.
const (
	Africa                      UNRegionOrSubregion = "Africa"
	Americas                    UNRegionOrSubregion = "Americas"
	Asia                        UNRegionOrSubregion = "Asia"
	AustraliaAndNewZealand      UNRegionOrSubregion = "Australia and New Zealand"
	CentralAsia                 UNRegionOrSubregion = "Central Asia"
	EasternAsia                 UNRegionOrSubregion = "Eastern Asia"
	EasternEurope               UNRegionOrSubregion = "Eastern Europe"
	Europe                      UNRegionOrSubregion = "Europe"
	LatinAmericaAndTheCaribbean UNRegionOrSubregion = "Latin America and the Caribbean"
	Melanesia                   UNRegionOrSubregion = "Melanesia"
	Micronesia                  UNRegionOrSubregion = "Micronesia"
	NorthernAfrica              UNRegionOrSubregion = "Northern Africa"
	NorthernAmerica             UNRegionOrSubregion = "Northern America"
	NorthernEurope              UNRegionOrSubregion = "Northern Europe"
	Oceania                     UNRegionOrSubregion = "Oceania"
	Polynesia                   UNRegionOrSubregion = "Polynesia"
	SouthEasternAsia            UNRegionOrSubregion = "South-eastern Asia"
	SouthernAsia                UNRegionOrSubregion = "Southern Asia"
	SouthernEurope              UNRegionOrSubregion = "Southern Europe"
	SubSaharanAfrica            UNRegionOrSubregion = "Sub-Saharan Africa"
	WesternAsia                 UNRegionOrSubregion = "Western Asia"
	WesternEurope               UNRegionOrSubregion = "Western Europe"
)

// AccessDenied Response with an error code of `AccessDenied`. See Chapter "Error Codes" of the Tech Specs for mor details.
type AccessDenied struct {
	// Code Error code enum for AccessDenied responses
	Code    AccessDeniedCode `json:"code"`
	Message string           `json:"message"`
}

// AccessDeniedCode Error code enum for AccessDenied responses
type AccessDeniedCode string

// Assurance Data Type "Assurance" of Spec Version 2
type Assurance struct {
	Assurance    bool               `json:"assurance"`
	Boundary     *AssuranceBoundary `json:"boundary,omitempty"`
	Comments     *string            `json:"comments,omitempty"`
	CompletedAt  *time.Time         `json:"completedAt,omitempty"`
	Coverage     *AssuranceCoverage `json:"coverage,omitempty"`
	Level        *AssuranceLevel    `json:"level,omitempty"`
	ProviderName string             `json:"providerName"`
	StandardName *string            `json:"standardName,omitempty"`
}

// AssuranceBoundary defines model for AssuranceBoundary.
type AssuranceBoundary string

// AssuranceCoverage defines model for AssuranceCoverage.
type AssuranceCoverage string

// AssuranceLevel defines model for AssuranceLevel.
type AssuranceLevel string

// BadRequest Response with an error code of `BadRequest`. See Chapter "Error Codes" of the Tech Specs for mor details.
type BadRequest struct {
	// Code Error code enum for BadRequest responses
	Code    BadRequestCode `json:"code"`
	Message string         `json:"message"`
}

// BadRequestCode Error code enum for BadRequest responses
type BadRequestCode string

// BiogenicAccountingMethodology defines model for BiogenicAccountingMethodology.
type BiogenicAccountingMethodology string

// CarbonFootprint Data Type "CarbonFootprint" of Spec Version 2
type CarbonFootprint struct {
	AircraftGHGEmissions          *PositiveDecimal               `json:"aircraftGhgEmissions,omitempty"`
	AllocationRulesDescription    *string                        `json:"allocationRulesDescription,omitempty"`
	Assurance                     *Assurance                     `json:"assurance,omitempty"`
	BiogenicAccountingMethodology *BiogenicAccountingMethodology `json:"biogenicAccountingMethodology,omitempty"`
	BiogenicCarbonContent         PositiveDecimal                `json:"biogenicCarbonContent"`
	BiogenicCarbonWithdrawal      *NegativeDecimal               `json:"biogenicCarbonWithdrawal,omitempty"`
	BoundaryProcessesDescription  string                         `json:"boundaryProcessesDescription"`
	CharacterizationFactors       CharacterizationFactors        `json:"characterizationFactors"`
	CrossSectoralStandardsUsed    CrossSectoralStandardSet       `json:"crossSectoralStandardsUsed"`
	DLUCGHGEmissions              *PositiveDecimal               `json:"dLucGhgEmissions,omitempty"`

	// DeclaredUnit Data Type "DeclaredUnit" of Spec Version 2
	DeclaredUnit                 DeclaredUnit             `json:"declaredUnit"`
	Dqi                          *DataQualityIndicators   `json:"dqi,omitempty"`
	ExemptedEmissionsDescription string                   `json:"exemptedEmissionsDescription"`
	ExemptedEmissionsPercent     ExemptedEmissionsPercent `json:"exemptedEmissionsPercent"`
	FossilCarbonContent          PositiveDecimal          `json:"fossilCarbonContent"`
	FossilGHGEmissions           PositiveDecimal          `json:"fossilGhgEmissions"`
	GeographyCountry             *ISO3166CC               `json:"geographyCountry,omitempty"`
	GeographyCountrySubdivision  *NonEmptyString          `json:"geographyCountrySubdivision,omitempty"`

	// GeographyRegionOrSubregion List of UN regions and subregions
	GeographyRegionOrSubregion         *UNRegionOrSubregion               `json:"geographyRegionOrSubregion,omitempty"`
	ILUCGHGEmissions                   *PositiveDecimal                   `json:"iLucGhgEmissions,omitempty"`
	IpccCharacterizationFactorsSources IpccCharacterizationFactorsSources `json:"ipccCharacterizationFactorsSources"`
	LandManagementGHGEmissions         *PositiveDecimal                   `json:"landManagementGhgEmissions,omitempty"`
	OtherBiogenicGHGEmissions          *PositiveDecimal                   `json:"otherBiogenicGhgEmissions,omitempty"`
	PCFExcludingBiogenic               PositiveDecimal                    `json:"pCfExcludingBiogenic"`
	PCFIncludingBiogenic               *Decimal                           `json:"pCfIncludingBiogenic,omitempty"`
	PackagingEmissionsIncluded         bool                               `json:"packagingEmissionsIncluded"`
	PackagingGHGEmissions              *PositiveDecimal                   `json:"packagingGhgEmissions,omitempty"`
	PrimaryDataShare                   *Percent                           `json:"primaryDataShare,omitempty"`
	ProductOrSectorSpecificRules       *ProductOrSectorSpecificRuleSet    `json:"productOrSectorSpecificRules,omitempty"`
	ReferencePeriodEnd                 time.Time                          `json:"referencePeriodEnd"`
	ReferencePeriodStart               time.Time                          `json:"referencePeriodStart"`
	SecondaryEmissionFactorSources     EmissionFactorDSSet                `json:"secondaryEmissionFactorSources,omitempty"`
	UncertaintyAssessmentDescription   *string                            `json:"uncertaintyAssessmentDescription,omitempty"`
	UnitaryProductAmount               StrictlyPositiveDecimal            `json:"unitaryProductAmount"`
}

// CharacterizationFactors defines model for CharacterizationFactors.
type CharacterizationFactors string

// CompanyIDSet defines model for CompanyIdSet.
type CompanyIDSet = []string

// CrossSectoralStandard Deprecated Data Type "CrossSectoralStandard" of Spec Version 2, to be removed in v3, used in `CrossSectoralStandardsSet`s to populate `crossSectoralSectoralStandardsUsed` (also deprecated).
type CrossSectoralStandard string

// CrossSectoralStandardSet defines model for CrossSectoralStandardSet.
type CrossSectoralStandardSet = []CrossSectoralStandard

// DataModelExtension defines model for DataModelExtension.
type DataModelExtension struct {
	Data          json.RawMessage `json:"data"`
	DataSchema    string          `json:"dataSchema"`
	Documentation *string         `json:"documentation,omitempty"`
	SpecVersion   VersionString   `json:"specVersion"`
}

// DataQualityIndicators Data Type "DataQualityIndicators" of Spec Version 2
type DataQualityIndicators struct {
	CompletenessDQR  FloatBetween1And3 `json:"completenessDQR"`
	CoveragePercent  Percent           `json:"coveragePercent"`
	GeographicalDQR  FloatBetween1And3 `json:"geographicalDQR"`
	ReliabilityDQR   FloatBetween1And3 `json:"reliabilityDQR"`
	TechnologicalDQR FloatBetween1And3 `json:"technologicalDQR"`
	TemporalDQR      FloatBetween1And3 `json:"temporalDQR"`
}

// Decimal defines model for Decimal.
type Decimal = string

// DeclaredUnit Data Type "DeclaredUnit" of Spec Version 2
type DeclaredUnit string

// EmissionFactorDS defines model for EmissionFactorDS.
type EmissionFactorDS struct {
	Name    NonEmptyString `json:"name"`
	Version NonEmptyString `json:"version"`
}

// EmissionFactorDSSet defines model for EmissionFactorDSSet.
type EmissionFactorDSSet = []EmissionFactorDS

// EnergyCarrier defines model for EnergyCarrier.
type EnergyCarrier struct {
	EmissionFactorTTW     Decimal                `json:"emissionFactorTTW"`
	EmissionFactorWTW     Decimal                `json:"emissionFactorWTW"`
	EnergyCarrier         EnergyCarrierType      `json:"energyCarrier"`
	EnergyConsumption     *Decimal               `json:"energyConsumption,omitempty"`
	EnergyConsumptionUnit *EnergyConsumptionUnit `json:"energyConsumptionUnit,omitempty"`
	Feedstocks            []Feedstock            `json:"feedstocks,omitempty"`
	RelativeShare         Decimal                `json:"relativeShare"`
}

// EnergyCarrierType defines model for EnergyCarrierType.
type EnergyCarrierType string

// EnergyConsumptionUnit defines model for EnergyConsumptionUnit.
type EnergyConsumptionUnit string

// ExemptedEmissionsPercent defines model for ExemptedEmissionsPercent.
type ExemptedEmissionsPercent = float64

// Feedstock defines model for Feedstock.
type Feedstock struct {
	Feedstock        FeedstockType `json:"feedstock"`
	FeedstockShare   *Decimal      `json:"feedstockShare,omitempty"`
	RegionProvenance *string       `json:"regionProvenance,omitempty"`
}

// FeedstockType defines model for FeedstockType.
type FeedstockType string

// FloatBetween1And3 defines model for FloatBetween1And3.
type FloatBetween1And3 = float32

// GenericURN defines model for GenericURN.
type GenericURN = string

// GlecDistance defines model for GlecDistance.
type GlecDistance struct {
	Actual *Decimal `json:"actual,omitempty"`
	GCD    *Decimal `json:"gcd,omitempty"`
	SFD    *Decimal `json:"sfd,omitempty"`
}

// ISO3166CC defines model for ISO3166CC.
type ISO3166CC = string

// IataCode defines model for IataCode.
type IataCode = string

// IpccCharacterizationFactorsSource defines model for IpccCharacterizationFactorsSource.
type IpccCharacterizationFactorsSource = string

// IpccCharacterizationFactorsSources defines model for IpccCharacterizationFactorsSources.
type IpccCharacterizationFactorsSources = []string

// Location defines model for Location.
type Location struct {
	City    string    `json:"city"`
	Country ISO3166CC `json:"country"`
	Iata    *IataCode `json:"iata,omitempty"`
	Lat     *Decimal  `json:"lat,omitempty"`
	Lng     *Decimal  `json:"lng,omitempty"`
	Locode  *Locode   `json:"locode,omitempty"`
	Street  *string   `json:"street,omitempty"`
	Uic     *UicCode  `json:"uic,omitempty"`
	Zip     *string   `json:"zip,omitempty"`
}

// Locode defines model for Locode.
type Locode = string

// NegativeDecimal defines model for NegativeDecimal.
type NegativeDecimal = string

// NoSuchFootprint Response with an error code of `NoSuchFootprint`. See Chapter "Error Codes" of the Tech Specs for mor details.
type NoSuchFootprint struct {
	// Code Error code enum for NoSuchFootprint responses
	Code    NoSuchFootprintCode `json:"code"`
	Message string              `json:"message"`
}

// NoSuchFootprintCode Error code enum for NoSuchFootprint responses
type NoSuchFootprintCode string

// NonEmptyPfIDVec defines model for NonEmptyPfIdVec.
type NonEmptyPfIDVec = []string

// NonEmptyString defines model for NonEmptyString.
type NonEmptyString = string

// NonEmptyStringVec defines model for NonEmptyStringVec.
type NonEmptyStringVec = []string

// NonEmptyVecForEnergyCarrier defines model for NonEmptyVec_for_EnergyCarrier.
type NonEmptyVecForEnergyCarrier = []EnergyCarrier

// NotImplemented Response with an error code of `NotImplemented`. See Chapter "Error Codes" of the Tech Specs for mor details.
type NotImplemented struct {
	// Code Error code enum for NotImplemented responses
	Code    NotImplementedCode `json:"code"`
	Message string             `json:"message"`
}

// NotImplementedCode Error code enum for NotImplemented responses
type NotImplementedCode string

// PFRequestEventBody defines model for PFRequestEventBody.
type PFRequestEventBody struct {
	Comment *string         `json:"comment,omitempty"`
	Pf      json.RawMessage `json:"pf"`
}

// PFUpdateEventBody defines model for PFUpdateEventBody.
type PFUpdateEventBody struct {
	PfIds []PfID `json:"pfIds"`
}

// PackagingOrTrEqType defines model for PackagingOrTrEqType.
type PackagingOrTrEqType string

// PathfinderEvent possible contents of `data` property of events - see tech specs section 6 for details
type PathfinderEvent struct {
	Data        *json.RawMessage `json:"data,omitempty"`
	ID          string           `json:"id"`
	Source      string           `json:"source"`
	SpecVersion string           `json:"specversion"`
	Time        time.Time        `json:"time"`
	Type        *string          `json:"type,omitempty"`
}

// PathfinderRequestEvent PF Request Event – see Tech Specs section 6.8.4.1
type PathfinderRequestEvent struct {
	Data        PFRequestEventBody         `json:"data"`
	ID          string                     `json:"id"`
	Source      string                     `json:"source"`
	SpecVersion string                     `json:"specversion"`
	Time        time.Time                  `json:"time"`
	Type        PathfinderRequestEventType `json:"type"`
}

// PathfinderRequestEventType defines model for PathfinderRequestEvent.Type.
type PathfinderRequestEventType string

// PathfinderUpdateEvent PF Update Event – see Tech Specs section 6.8.3
type PathfinderUpdateEvent struct {
	Data        PFUpdateEventBody         `json:"data"`
	ID          string                    `json:"id"`
	Source      string                    `json:"source"`
	SpecVersion string                    `json:"specversion"`
	Time        time.Time                 `json:"time"`
	Type        PathfinderUpdateEventType `json:"type"`
}

// PathfinderUpdateEventType defines model for PathfinderUpdateEvent.Type.
type PathfinderUpdateEventType string

// Percent defines model for Percent.
type Percent = float64

// PfID defines model for PfId.
type PfID = string

// PfIDParam defines model for PfIdParam.
type PfIDParam = PfID

// PfListingResponseInner HTTP Body of Action `ListFootprints`
type PfListingResponseInner struct {
	Data []ProductFootprintForILeapType `json:"data"`
}

// PfStatus defines model for PfStatus.
type PfStatus string

// PositiveDecimal defines model for PositiveDecimal.
type PositiveDecimal = string

// ProductFootprintResponse HTTP Body of Action `GetFootprint`
type ProductFootprintResponse struct {
	// Data Data Type "ProductFootprint" of Tech Spec Version 2
	Data ProductFootprintForILeapType `json:"data"`
}

// ProductFootprintForILeapType Data Type "ProductFootprint" of Tech Spec Version 2
type ProductFootprintForILeapType struct {
	Comment          string               `json:"comment"`
	CompanyIds       CompanyIDSet         `json:"companyIds"`
	CompanyName      NonEmptyString       `json:"companyName"`
	Created          time.Time            `json:"created"`
	Extensions       []DataModelExtension `json:"extensions,omitempty"`
	ID               PfID                 `json:"id"`
	OrganizationName *NonEmptyString      `json:"organizationName,omitempty"`

	// Pcf Data Type "CarbonFootprint" of Spec Version 2
	Pcf                 CarbonFootprint `json:"pcf"`
	PrecedingPfIds      NonEmptyPfIDVec `json:"precedingPfIds,omitempty"`
	ProductCategoryCpc  NonEmptyString  `json:"productCategoryCpc"`
	ProductDescription  string          `json:"productDescription"`
	ProductIds          ProductIDSet    `json:"productIds"`
	ProductNameCompany  NonEmptyString  `json:"productNameCompany"`
	SpecVersion         VersionString   `json:"specVersion"`
	Status              PfStatus        `json:"status"`
	StatusComment       *string         `json:"statusComment,omitempty"`
	Updated             *time.Time      `json:"updated,omitempty"`
	ValidityPeriodEnd   *time.Time      `json:"validityPeriodEnd,omitempty"`
	ValidityPeriodStart *time.Time      `json:"validityPeriodStart,omitempty"`
	Version             VersionInteger  `json:"version"`
}

// ProductIDSet defines model for ProductIdSet.
type ProductIDSet = []string

// ProductOrSectorSpecificRule defines model for ProductOrSectorSpecificRule.
type ProductOrSectorSpecificRule struct {
	Operator          ProductOrSectorSpecificRuleOperator `json:"operator"`
	OtherOperatorName *NonEmptyString                     `json:"otherOperatorName,omitempty"`
	RuleNames         NonEmptyStringVec                   `json:"ruleNames"`
}

// ProductOrSectorSpecificRuleOperator defines model for ProductOrSectorSpecificRuleOperator.
type ProductOrSectorSpecificRuleOperator string

// ProductOrSectorSpecificRuleSet defines model for ProductOrSectorSpecificRuleSet.
type ProductOrSectorSpecificRuleSet = []ProductOrSectorSpecificRule

// StrictlyPositiveDecimal defines model for StrictlyPositiveDecimal.
type StrictlyPositiveDecimal = string

// TAD Data Type "Transport Activity Data" of the iLEAP Technical Specifications
type TAD struct {
	ActivityID            string                      `json:"activityId"`
	ArrivalAt             time.Time                   `json:"arrivalAt"`
	ConsignmentIds        []string                    `json:"consignmentIds"`
	DepartureAt           time.Time                   `json:"departureAt"`
	Destination           Location                    `json:"destination"`
	Distance              GlecDistance                `json:"distance"`
	EmptyDistanceFactor   *Decimal                    `json:"emptyDistanceFactor,omitempty"`
	EnergyCarriers        NonEmptyVecForEnergyCarrier `json:"energyCarriers,omitempty"`
	LoadFactor            *Decimal                    `json:"loadFactor,omitempty"`
	Mass                  *Decimal                    `json:"mass,omitempty"`
	Mode                  TransportMode               `json:"mode"`
	Origin                Location                    `json:"origin"`
	PackagingOrTrEqAmount *uint                       `json:"packagingOrTrEqAmount,omitempty"`
	PackagingOrTrEqType   *PackagingOrTrEqType        `json:"packagingOrTrEqType,omitempty"`
	TemperatureControl    *TadTempControl             `json:"temperatureControl,omitempty"`
}

// TadListingResponseInner HTTP Body of Action `TransportActivityData`
type TadListingResponseInner struct {
	Data []TAD `json:"data"`
}

// TadTempControl defines model for TadTempControl.
type TadTempControl string

// TransportMode defines model for TransportMode.
type TransportMode string

// UNRegionOrSubregion List of UN regions and subregions
type UNRegionOrSubregion string

// UicCode defines model for UicCode.
type UicCode = string

// VersionInteger defines model for VersionInteger.
type VersionInteger = int32

// VersionString defines model for VersionString.
type VersionString = string
