// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/carbon_footprint.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CarbonFootprint is the PACT CarbonFootprint data type.
type CarbonFootprint struct {
	state                                         protoimpl.MessageState                          `protogen:"opaque.v1"`
	xxx_hidden_AircraftGhgEmissions               *string                                         `protobuf:"bytes,1,opt,name=aircraft_ghg_emissions,json=aircraftGhgEmissions"`
	xxx_hidden_AllocationRulesDescription         *string                                         `protobuf:"bytes,2,opt,name=allocation_rules_description,json=allocationRulesDescription"`
	xxx_hidden_Assurance                          *CarbonFootprint_Assurance                      `protobuf:"bytes,3,opt,name=assurance"`
	xxx_hidden_BiogenicAccountingMethodology      *string                                         `protobuf:"bytes,4,opt,name=biogenic_accounting_methodology,json=biogenicAccountingMethodology"`
	xxx_hidden_BiogenicCarbonContent              *string                                         `protobuf:"bytes,5,opt,name=biogenic_carbon_content,json=biogenicCarbonContent"`
	xxx_hidden_BiogenicCarbonWithdrawal           *string                                         `protobuf:"bytes,6,opt,name=biogenic_carbon_withdrawal,json=biogenicCarbonWithdrawal"`
	xxx_hidden_BoundaryProcessesDescription       *string                                         `protobuf:"bytes,7,opt,name=boundary_processes_description,json=boundaryProcessesDescription"`
	xxx_hidden_CharacterizationFactors            *string                                         `protobuf:"bytes,8,opt,name=characterization_factors,json=characterizationFactors"`
	xxx_hidden_CrossSectoralStandardsUsed         []string                                        `protobuf:"bytes,9,rep,name=cross_sectoral_standards_used,json=crossSectoralStandardsUsed"`
	xxx_hidden_DLucGhgEmissions                   *string                                         `protobuf:"bytes,10,opt,name=d_luc_ghg_emissions,json=dLucGhgEmissions"`
	xxx_hidden_DeclaredUnit                       *string                                         `protobuf:"bytes,11,opt,name=declared_unit,json=declaredUnit"`
	xxx_hidden_Dqi                                *CarbonFootprint_DataQualityIndicators          `protobuf:"bytes,12,opt,name=dqi"`
	xxx_hidden_ExemptedEmissionsDescription       *string                                         `protobuf:"bytes,13,opt,name=exempted_emissions_description,json=exemptedEmissionsDescription"`
	xxx_hidden_ExemptedEmissionsPercent           float64                                         `protobuf:"fixed64,14,opt,name=exempted_emissions_percent,json=exemptedEmissionsPercent"`
	xxx_hidden_FossilCarbonContent                *string                                         `protobuf:"bytes,15,opt,name=fossil_carbon_content,json=fossilCarbonContent"`
	xxx_hidden_FossilGhgEmissions                 *string                                         `protobuf:"bytes,16,opt,name=fossil_ghg_emissions,json=fossilGhgEmissions"`
	xxx_hidden_GeographyCountry                   *string                                         `protobuf:"bytes,17,opt,name=geography_country,json=geographyCountry"`
	xxx_hidden_GeographyCountrySubdivision        *string                                         `protobuf:"bytes,18,opt,name=geography_country_subdivision,json=geographyCountrySubdivision"`
	xxx_hidden_GeographyRegionOrSubregion         *string                                         `protobuf:"bytes,19,opt,name=geography_region_or_subregion,json=geographyRegionOrSubregion"`
	xxx_hidden_ILucGhgEmissions                   *string                                         `protobuf:"bytes,20,opt,name=i_luc_ghg_emissions,json=iLucGhgEmissions"`
	xxx_hidden_IpccCharacterizationFactorsSources []string                                        `protobuf:"bytes,21,rep,name=ipcc_characterization_factors_sources,json=ipccCharacterizationFactorsSources"`
	xxx_hidden_LandManagementGhgEmissions         *string                                         `protobuf:"bytes,22,opt,name=land_management_ghg_emissions,json=landManagementGhgEmissions"`
	xxx_hidden_OtherBiogenicGhgEmissions          *string                                         `protobuf:"bytes,23,opt,name=other_biogenic_ghg_emissions,json=otherBiogenicGhgEmissions"`
	xxx_hidden_PCfExcludingBiogenic               *string                                         `protobuf:"bytes,24,opt,name=p_cf_excluding_biogenic,json=pCfExcludingBiogenic"`
	xxx_hidden_PCfIncludingBiogenic               *string                                         `protobuf:"bytes,25,opt,name=p_cf_including_biogenic,json=pCfIncludingBiogenic"`
	xxx_hidden_PackagingEmissionsIncluded         bool                                            `protobuf:"varint,26,opt,name=packaging_emissions_included,json=packagingEmissionsIncluded"`
	xxx_hidden_PackagingGhgEmissions              *string                                         `protobuf:"bytes,27,opt,name=packaging_ghg_emissions,json=packagingGhgEmissions"`
	xxx_hidden_PrimaryDataShare                   float64                                         `protobuf:"fixed64,28,opt,name=primary_data_share,json=primaryDataShare"`
	xxx_hidden_ProductOrSectorSpecificRules       *[]*CarbonFootprint_ProductOrSectorSpecificRule `protobuf:"bytes,29,rep,name=product_or_sector_specific_rules,json=productOrSectorSpecificRules"`
	xxx_hidden_ReferencePeriodEnd                 *timestamppb.Timestamp                          `protobuf:"bytes,30,opt,name=reference_period_end,json=referencePeriodEnd"`
	xxx_hidden_ReferencePeriodStart               *timestamppb.Timestamp                          `protobuf:"bytes,31,opt,name=reference_period_start,json=referencePeriodStart"`
	xxx_hidden_SecondaryEmissionFactorSources     *[]*CarbonFootprint_EmissionFactorDS            `protobuf:"bytes,32,rep,name=secondary_emission_factor_sources,json=secondaryEmissionFactorSources"`
	xxx_hidden_UncertaintyAssessmentDescription   *string                                         `protobuf:"bytes,33,opt,name=uncertainty_assessment_description,json=uncertaintyAssessmentDescription"`
	xxx_hidden_UnitaryProductAmount               *string                                         `protobuf:"bytes,34,opt,name=unitary_product_amount,json=unitaryProductAmount"`
	XXX_raceDetectHookData                        protoimpl.RaceDetectHookData
	XXX_presence                                  [2]uint32
	unknownFields                                 protoimpl.UnknownFields
	sizeCache                                     protoimpl.SizeCache
}

func (x *CarbonFootprint) Reset() {
	*x = CarbonFootprint{}
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarbonFootprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarbonFootprint) ProtoMessage() {}

func (x *CarbonFootprint) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CarbonFootprint) GetAircraftGhgEmissions() string {
	if x != nil {
		if x.xxx_hidden_AircraftGhgEmissions != nil {
			return *x.xxx_hidden_AircraftGhgEmissions
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetAllocationRulesDescription() string {
	if x != nil {
		if x.xxx_hidden_AllocationRulesDescription != nil {
			return *x.xxx_hidden_AllocationRulesDescription
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetAssurance() *CarbonFootprint_Assurance {
	if x != nil {
		return x.xxx_hidden_Assurance
	}
	return nil
}

func (x *CarbonFootprint) GetBiogenicAccountingMethodology() string {
	if x != nil {
		if x.xxx_hidden_BiogenicAccountingMethodology != nil {
			return *x.xxx_hidden_BiogenicAccountingMethodology
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetBiogenicCarbonContent() string {
	if x != nil {
		if x.xxx_hidden_BiogenicCarbonContent != nil {
			return *x.xxx_hidden_BiogenicCarbonContent
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetBiogenicCarbonWithdrawal() string {
	if x != nil {
		if x.xxx_hidden_BiogenicCarbonWithdrawal != nil {
			return *x.xxx_hidden_BiogenicCarbonWithdrawal
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetBoundaryProcessesDescription() string {
	if x != nil {
		if x.xxx_hidden_BoundaryProcessesDescription != nil {
			return *x.xxx_hidden_BoundaryProcessesDescription
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetCharacterizationFactors() string {
	if x != nil {
		if x.xxx_hidden_CharacterizationFactors != nil {
			return *x.xxx_hidden_CharacterizationFactors
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetCrossSectoralStandardsUsed() []string {
	if x != nil {
		return x.xxx_hidden_CrossSectoralStandardsUsed
	}
	return nil
}

func (x *CarbonFootprint) GetDLucGhgEmissions() string {
	if x != nil {
		if x.xxx_hidden_DLucGhgEmissions != nil {
			return *x.xxx_hidden_DLucGhgEmissions
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetDeclaredUnit() string {
	if x != nil {
		if x.xxx_hidden_DeclaredUnit != nil {
			return *x.xxx_hidden_DeclaredUnit
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetDqi() *CarbonFootprint_DataQualityIndicators {
	if x != nil {
		return x.xxx_hidden_Dqi
	}
	return nil
}

func (x *CarbonFootprint) GetExemptedEmissionsDescription() string {
	if x != nil {
		if x.xxx_hidden_ExemptedEmissionsDescription != nil {
			return *x.xxx_hidden_ExemptedEmissionsDescription
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetExemptedEmissionsPercent() float64 {
	if x != nil {
		return x.xxx_hidden_ExemptedEmissionsPercent
	}
	return 0
}

func (x *CarbonFootprint) GetFossilCarbonContent() string {
	if x != nil {
		if x.xxx_hidden_FossilCarbonContent != nil {
			return *x.xxx_hidden_FossilCarbonContent
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetFossilGhgEmissions() string {
	if x != nil {
		if x.xxx_hidden_FossilGhgEmissions != nil {
			return *x.xxx_hidden_FossilGhgEmissions
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetGeographyCountry() string {
	if x != nil {
		if x.xxx_hidden_GeographyCountry != nil {
			return *x.xxx_hidden_GeographyCountry
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetGeographyCountrySubdivision() string {
	if x != nil {
		if x.xxx_hidden_GeographyCountrySubdivision != nil {
			return *x.xxx_hidden_GeographyCountrySubdivision
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetGeographyRegionOrSubregion() string {
	if x != nil {
		if x.xxx_hidden_GeographyRegionOrSubregion != nil {
			return *x.xxx_hidden_GeographyRegionOrSubregion
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetILucGhgEmissions() string {
	if x != nil {
		if x.xxx_hidden_ILucGhgEmissions != nil {
			return *x.xxx_hidden_ILucGhgEmissions
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetIpccCharacterizationFactorsSources() []string {
	if x != nil {
		return x.xxx_hidden_IpccCharacterizationFactorsSources
	}
	return nil
}

func (x *CarbonFootprint) GetLandManagementGhgEmissions() string {
	if x != nil {
		if x.xxx_hidden_LandManagementGhgEmissions != nil {
			return *x.xxx_hidden_LandManagementGhgEmissions
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetOtherBiogenicGhgEmissions() string {
	if x != nil {
		if x.xxx_hidden_OtherBiogenicGhgEmissions != nil {
			return *x.xxx_hidden_OtherBiogenicGhgEmissions
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetPCfExcludingBiogenic() string {
	if x != nil {
		if x.xxx_hidden_PCfExcludingBiogenic != nil {
			return *x.xxx_hidden_PCfExcludingBiogenic
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetPCfIncludingBiogenic() string {
	if x != nil {
		if x.xxx_hidden_PCfIncludingBiogenic != nil {
			return *x.xxx_hidden_PCfIncludingBiogenic
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetPackagingEmissionsIncluded() bool {
	if x != nil {
		return x.xxx_hidden_PackagingEmissionsIncluded
	}
	return false
}

func (x *CarbonFootprint) GetPackagingGhgEmissions() string {
	if x != nil {
		if x.xxx_hidden_PackagingGhgEmissions != nil {
			return *x.xxx_hidden_PackagingGhgEmissions
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetPrimaryDataShare() float64 {
	if x != nil {
		return x.xxx_hidden_PrimaryDataShare
	}
	return 0
}

func (x *CarbonFootprint) GetProductOrSectorSpecificRules() []*CarbonFootprint_ProductOrSectorSpecificRule {
	if x != nil {
		if x.xxx_hidden_ProductOrSectorSpecificRules != nil {
			return *x.xxx_hidden_ProductOrSectorSpecificRules
		}
	}
	return nil
}

func (x *CarbonFootprint) GetReferencePeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ReferencePeriodEnd
	}
	return nil
}

func (x *CarbonFootprint) GetReferencePeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ReferencePeriodStart
	}
	return nil
}

func (x *CarbonFootprint) GetSecondaryEmissionFactorSources() []*CarbonFootprint_EmissionFactorDS {
	if x != nil {
		if x.xxx_hidden_SecondaryEmissionFactorSources != nil {
			return *x.xxx_hidden_SecondaryEmissionFactorSources
		}
	}
	return nil
}

func (x *CarbonFootprint) GetUncertaintyAssessmentDescription() string {
	if x != nil {
		if x.xxx_hidden_UncertaintyAssessmentDescription != nil {
			return *x.xxx_hidden_UncertaintyAssessmentDescription
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) GetUnitaryProductAmount() string {
	if x != nil {
		if x.xxx_hidden_UnitaryProductAmount != nil {
			return *x.xxx_hidden_UnitaryProductAmount
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint) SetAircraftGhgEmissions(v string) {
	x.xxx_hidden_AircraftGhgEmissions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 34)
}

func (x *CarbonFootprint) SetAllocationRulesDescription(v string) {
	x.xxx_hidden_AllocationRulesDescription = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 34)
}

func (x *CarbonFootprint) SetAssurance(v *CarbonFootprint_Assurance) {
	x.xxx_hidden_Assurance = v
}

func (x *CarbonFootprint) SetBiogenicAccountingMethodology(v string) {
	x.xxx_hidden_BiogenicAccountingMethodology = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 34)
}

func (x *CarbonFootprint) SetBiogenicCarbonContent(v string) {
	x.xxx_hidden_BiogenicCarbonContent = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 34)
}

func (x *CarbonFootprint) SetBiogenicCarbonWithdrawal(v string) {
	x.xxx_hidden_BiogenicCarbonWithdrawal = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 34)
}

func (x *CarbonFootprint) SetBoundaryProcessesDescription(v string) {
	x.xxx_hidden_BoundaryProcessesDescription = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 34)
}

func (x *CarbonFootprint) SetCharacterizationFactors(v string) {
	x.xxx_hidden_CharacterizationFactors = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 34)
}

func (x *CarbonFootprint) SetCrossSectoralStandardsUsed(v []string) {
	x.xxx_hidden_CrossSectoralStandardsUsed = v
}

func (x *CarbonFootprint) SetDLucGhgEmissions(v string) {
	x.xxx_hidden_DLucGhgEmissions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 34)
}

func (x *CarbonFootprint) SetDeclaredUnit(v string) {
	x.xxx_hidden_DeclaredUnit = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 34)
}

func (x *CarbonFootprint) SetDqi(v *CarbonFootprint_DataQualityIndicators) {
	x.xxx_hidden_Dqi = v
}

func (x *CarbonFootprint) SetExemptedEmissionsDescription(v string) {
	x.xxx_hidden_ExemptedEmissionsDescription = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 34)
}

func (x *CarbonFootprint) SetExemptedEmissionsPercent(v float64) {
	x.xxx_hidden_ExemptedEmissionsPercent = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 34)
}

func (x *CarbonFootprint) SetFossilCarbonContent(v string) {
	x.xxx_hidden_FossilCarbonContent = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 34)
}

func (x *CarbonFootprint) SetFossilGhgEmissions(v string) {
	x.xxx_hidden_FossilGhgEmissions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 34)
}

func (x *CarbonFootprint) SetGeographyCountry(v string) {
	x.xxx_hidden_GeographyCountry = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 16, 34)
}

func (x *CarbonFootprint) SetGeographyCountrySubdivision(v string) {
	x.xxx_hidden_GeographyCountrySubdivision = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 17, 34)
}

func (x *CarbonFootprint) SetGeographyRegionOrSubregion(v string) {
	x.xxx_hidden_GeographyRegionOrSubregion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 18, 34)
}

func (x *CarbonFootprint) SetILucGhgEmissions(v string) {
	x.xxx_hidden_ILucGhgEmissions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 19, 34)
}

func (x *CarbonFootprint) SetIpccCharacterizationFactorsSources(v []string) {
	x.xxx_hidden_IpccCharacterizationFactorsSources = v
}

func (x *CarbonFootprint) SetLandManagementGhgEmissions(v string) {
	x.xxx_hidden_LandManagementGhgEmissions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 21, 34)
}

func (x *CarbonFootprint) SetOtherBiogenicGhgEmissions(v string) {
	x.xxx_hidden_OtherBiogenicGhgEmissions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 22, 34)
}

func (x *CarbonFootprint) SetPCfExcludingBiogenic(v string) {
	x.xxx_hidden_PCfExcludingBiogenic = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 23, 34)
}

func (x *CarbonFootprint) SetPCfIncludingBiogenic(v string) {
	x.xxx_hidden_PCfIncludingBiogenic = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 24, 34)
}

func (x *CarbonFootprint) SetPackagingEmissionsIncluded(v bool) {
	x.xxx_hidden_PackagingEmissionsIncluded = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 25, 34)
}

func (x *CarbonFootprint) SetPackagingGhgEmissions(v string) {
	x.xxx_hidden_PackagingGhgEmissions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 26, 34)
}

func (x *CarbonFootprint) SetPrimaryDataShare(v float64) {
	x.xxx_hidden_PrimaryDataShare = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 27, 34)
}

func (x *CarbonFootprint) SetProductOrSectorSpecificRules(v []*CarbonFootprint_ProductOrSectorSpecificRule) {
	x.xxx_hidden_ProductOrSectorSpecificRules = &v
}

func (x *CarbonFootprint) SetReferencePeriodEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_ReferencePeriodEnd = v
}

func (x *CarbonFootprint) SetReferencePeriodStart(v *timestamppb.Timestamp) {
	x.xxx_hidden_ReferencePeriodStart = v
}

func (x *CarbonFootprint) SetSecondaryEmissionFactorSources(v []*CarbonFootprint_EmissionFactorDS) {
	x.xxx_hidden_SecondaryEmissionFactorSources = &v
}

func (x *CarbonFootprint) SetUncertaintyAssessmentDescription(v string) {
	x.xxx_hidden_UncertaintyAssessmentDescription = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 32, 34)
}

func (x *CarbonFootprint) SetUnitaryProductAmount(v string) {
	x.xxx_hidden_UnitaryProductAmount = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 33, 34)
}

func (x *CarbonFootprint) HasAircraftGhgEmissions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CarbonFootprint) HasAllocationRulesDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CarbonFootprint) HasAssurance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Assurance != nil
}

func (x *CarbonFootprint) HasBiogenicAccountingMethodology() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CarbonFootprint) HasBiogenicCarbonContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CarbonFootprint) HasBiogenicCarbonWithdrawal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CarbonFootprint) HasBoundaryProcessesDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *CarbonFootprint) HasCharacterizationFactors() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *CarbonFootprint) HasDLucGhgEmissions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *CarbonFootprint) HasDeclaredUnit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *CarbonFootprint) HasDqi() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Dqi != nil
}

func (x *CarbonFootprint) HasExemptedEmissionsDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *CarbonFootprint) HasExemptedEmissionsPercent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *CarbonFootprint) HasFossilCarbonContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *CarbonFootprint) HasFossilGhgEmissions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *CarbonFootprint) HasGeographyCountry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 16)
}

func (x *CarbonFootprint) HasGeographyCountrySubdivision() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 17)
}

func (x *CarbonFootprint) HasGeographyRegionOrSubregion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 18)
}

func (x *CarbonFootprint) HasILucGhgEmissions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 19)
}

func (x *CarbonFootprint) HasLandManagementGhgEmissions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 21)
}

func (x *CarbonFootprint) HasOtherBiogenicGhgEmissions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 22)
}

func (x *CarbonFootprint) HasPCfExcludingBiogenic() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 23)
}

func (x *CarbonFootprint) HasPCfIncludingBiogenic() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 24)
}

func (x *CarbonFootprint) HasPackagingEmissionsIncluded() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 25)
}

func (x *CarbonFootprint) HasPackagingGhgEmissions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 26)
}

func (x *CarbonFootprint) HasPrimaryDataShare() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 27)
}

func (x *CarbonFootprint) HasReferencePeriodEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReferencePeriodEnd != nil
}

func (x *CarbonFootprint) HasReferencePeriodStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReferencePeriodStart != nil
}

func (x *CarbonFootprint) HasUncertaintyAssessmentDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 32)
}

func (x *CarbonFootprint) HasUnitaryProductAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 33)
}

func (x *CarbonFootprint) ClearAircraftGhgEmissions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AircraftGhgEmissions = nil
}

func (x *CarbonFootprint) ClearAllocationRulesDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AllocationRulesDescription = nil
}

func (x *CarbonFootprint) ClearAssurance() {
	x.xxx_hidden_Assurance = nil
}

func (x *CarbonFootprint) ClearBiogenicAccountingMethodology() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_BiogenicAccountingMethodology = nil
}

func (x *CarbonFootprint) ClearBiogenicCarbonContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_BiogenicCarbonContent = nil
}

func (x *CarbonFootprint) ClearBiogenicCarbonWithdrawal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_BiogenicCarbonWithdrawal = nil
}

func (x *CarbonFootprint) ClearBoundaryProcessesDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_BoundaryProcessesDescription = nil
}

func (x *CarbonFootprint) ClearCharacterizationFactors() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_CharacterizationFactors = nil
}

func (x *CarbonFootprint) ClearDLucGhgEmissions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DLucGhgEmissions = nil
}

func (x *CarbonFootprint) ClearDeclaredUnit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_DeclaredUnit = nil
}

func (x *CarbonFootprint) ClearDqi() {
	x.xxx_hidden_Dqi = nil
}

func (x *CarbonFootprint) ClearExemptedEmissionsDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_ExemptedEmissionsDescription = nil
}

func (x *CarbonFootprint) ClearExemptedEmissionsPercent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_ExemptedEmissionsPercent = 0
}

func (x *CarbonFootprint) ClearFossilCarbonContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_FossilCarbonContent = nil
}

func (x *CarbonFootprint) ClearFossilGhgEmissions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_FossilGhgEmissions = nil
}

func (x *CarbonFootprint) ClearGeographyCountry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 16)
	x.xxx_hidden_GeographyCountry = nil
}

func (x *CarbonFootprint) ClearGeographyCountrySubdivision() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 17)
	x.xxx_hidden_GeographyCountrySubdivision = nil
}

func (x *CarbonFootprint) ClearGeographyRegionOrSubregion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 18)
	x.xxx_hidden_GeographyRegionOrSubregion = nil
}

func (x *CarbonFootprint) ClearILucGhgEmissions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 19)
	x.xxx_hidden_ILucGhgEmissions = nil
}

func (x *CarbonFootprint) ClearLandManagementGhgEmissions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 21)
	x.xxx_hidden_LandManagementGhgEmissions = nil
}

func (x *CarbonFootprint) ClearOtherBiogenicGhgEmissions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 22)
	x.xxx_hidden_OtherBiogenicGhgEmissions = nil
}

func (x *CarbonFootprint) ClearPCfExcludingBiogenic() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 23)
	x.xxx_hidden_PCfExcludingBiogenic = nil
}

func (x *CarbonFootprint) ClearPCfIncludingBiogenic() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 24)
	x.xxx_hidden_PCfIncludingBiogenic = nil
}

func (x *CarbonFootprint) ClearPackagingEmissionsIncluded() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 25)
	x.xxx_hidden_PackagingEmissionsIncluded = false
}

func (x *CarbonFootprint) ClearPackagingGhgEmissions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 26)
	x.xxx_hidden_PackagingGhgEmissions = nil
}

func (x *CarbonFootprint) ClearPrimaryDataShare() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 27)
	x.xxx_hidden_PrimaryDataShare = 0
}

func (x *CarbonFootprint) ClearReferencePeriodEnd() {
	x.xxx_hidden_ReferencePeriodEnd = nil
}

func (x *CarbonFootprint) ClearReferencePeriodStart() {
	x.xxx_hidden_ReferencePeriodStart = nil
}

func (x *CarbonFootprint) ClearUncertaintyAssessmentDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 32)
	x.xxx_hidden_UncertaintyAssessmentDescription = nil
}

func (x *CarbonFootprint) ClearUnitaryProductAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 33)
	x.xxx_hidden_UnitaryProductAmount = nil
}

type CarbonFootprint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AircraftGhgEmissions               *string
	AllocationRulesDescription         *string
	Assurance                          *CarbonFootprint_Assurance
	BiogenicAccountingMethodology      *string
	BiogenicCarbonContent              *string
	BiogenicCarbonWithdrawal           *string
	BoundaryProcessesDescription       *string
	CharacterizationFactors            *string
	CrossSectoralStandardsUsed         []string
	DLucGhgEmissions                   *string
	DeclaredUnit                       *string
	Dqi                                *CarbonFootprint_DataQualityIndicators
	ExemptedEmissionsDescription       *string
	ExemptedEmissionsPercent           *float64
	FossilCarbonContent                *string
	FossilGhgEmissions                 *string
	GeographyCountry                   *string
	GeographyCountrySubdivision        *string
	GeographyRegionOrSubregion         *string
	ILucGhgEmissions                   *string
	IpccCharacterizationFactorsSources []string
	LandManagementGhgEmissions         *string
	OtherBiogenicGhgEmissions          *string
	PCfExcludingBiogenic               *string
	PCfIncludingBiogenic               *string
	PackagingEmissionsIncluded         *bool
	PackagingGhgEmissions              *string
	PrimaryDataShare                   *float64
	ProductOrSectorSpecificRules       []*CarbonFootprint_ProductOrSectorSpecificRule
	ReferencePeriodEnd                 *timestamppb.Timestamp
	ReferencePeriodStart               *timestamppb.Timestamp
	SecondaryEmissionFactorSources     []*CarbonFootprint_EmissionFactorDS
	UncertaintyAssessmentDescription   *string
	UnitaryProductAmount               *string
}

func (b0 CarbonFootprint_builder) Build() *CarbonFootprint {
	m0 := &CarbonFootprint{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AircraftGhgEmissions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 34)
		x.xxx_hidden_AircraftGhgEmissions = b.AircraftGhgEmissions
	}
	if b.AllocationRulesDescription != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 34)
		x.xxx_hidden_AllocationRulesDescription = b.AllocationRulesDescription
	}
	x.xxx_hidden_Assurance = b.Assurance
	if b.BiogenicAccountingMethodology != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 34)
		x.xxx_hidden_BiogenicAccountingMethodology = b.BiogenicAccountingMethodology
	}
	if b.BiogenicCarbonContent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 34)
		x.xxx_hidden_BiogenicCarbonContent = b.BiogenicCarbonContent
	}
	if b.BiogenicCarbonWithdrawal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 34)
		x.xxx_hidden_BiogenicCarbonWithdrawal = b.BiogenicCarbonWithdrawal
	}
	if b.BoundaryProcessesDescription != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 34)
		x.xxx_hidden_BoundaryProcessesDescription = b.BoundaryProcessesDescription
	}
	if b.CharacterizationFactors != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 34)
		x.xxx_hidden_CharacterizationFactors = b.CharacterizationFactors
	}
	x.xxx_hidden_CrossSectoralStandardsUsed = b.CrossSectoralStandardsUsed
	if b.DLucGhgEmissions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 34)
		x.xxx_hidden_DLucGhgEmissions = b.DLucGhgEmissions
	}
	if b.DeclaredUnit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 34)
		x.xxx_hidden_DeclaredUnit = b.DeclaredUnit
	}
	x.xxx_hidden_Dqi = b.Dqi
	if b.ExemptedEmissionsDescription != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 34)
		x.xxx_hidden_ExemptedEmissionsDescription = b.ExemptedEmissionsDescription
	}
	if b.ExemptedEmissionsPercent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 34)
		x.xxx_hidden_ExemptedEmissionsPercent = *b.ExemptedEmissionsPercent
	}
	if b.FossilCarbonContent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 34)
		x.xxx_hidden_FossilCarbonContent = b.FossilCarbonContent
	}
	if b.FossilGhgEmissions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 34)
		x.xxx_hidden_FossilGhgEmissions = b.FossilGhgEmissions
	}
	if b.GeographyCountry != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 16, 34)
		x.xxx_hidden_GeographyCountry = b.GeographyCountry
	}
	if b.GeographyCountrySubdivision != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 17, 34)
		x.xxx_hidden_GeographyCountrySubdivision = b.GeographyCountrySubdivision
	}
	if b.GeographyRegionOrSubregion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 18, 34)
		x.xxx_hidden_GeographyRegionOrSubregion = b.GeographyRegionOrSubregion
	}
	if b.ILucGhgEmissions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 19, 34)
		x.xxx_hidden_ILucGhgEmissions = b.ILucGhgEmissions
	}
	x.xxx_hidden_IpccCharacterizationFactorsSources = b.IpccCharacterizationFactorsSources
	if b.LandManagementGhgEmissions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 21, 34)
		x.xxx_hidden_LandManagementGhgEmissions = b.LandManagementGhgEmissions
	}
	if b.OtherBiogenicGhgEmissions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 22, 34)
		x.xxx_hidden_OtherBiogenicGhgEmissions = b.OtherBiogenicGhgEmissions
	}
	if b.PCfExcludingBiogenic != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 23, 34)
		x.xxx_hidden_PCfExcludingBiogenic = b.PCfExcludingBiogenic
	}
	if b.PCfIncludingBiogenic != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 24, 34)
		x.xxx_hidden_PCfIncludingBiogenic = b.PCfIncludingBiogenic
	}
	if b.PackagingEmissionsIncluded != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 25, 34)
		x.xxx_hidden_PackagingEmissionsIncluded = *b.PackagingEmissionsIncluded
	}
	if b.PackagingGhgEmissions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 26, 34)
		x.xxx_hidden_PackagingGhgEmissions = b.PackagingGhgEmissions
	}
	if b.PrimaryDataShare != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 27, 34)
		x.xxx_hidden_PrimaryDataShare = *b.PrimaryDataShare
	}
	x.xxx_hidden_ProductOrSectorSpecificRules = &b.ProductOrSectorSpecificRules
	x.xxx_hidden_ReferencePeriodEnd = b.ReferencePeriodEnd
	x.xxx_hidden_ReferencePeriodStart = b.ReferencePeriodStart
	x.xxx_hidden_SecondaryEmissionFactorSources = &b.SecondaryEmissionFactorSources
	if b.UncertaintyAssessmentDescription != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 32, 34)
		x.xxx_hidden_UncertaintyAssessmentDescription = b.UncertaintyAssessmentDescription
	}
	if b.UnitaryProductAmount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 33, 34)
		x.xxx_hidden_UnitaryProductAmount = b.UnitaryProductAmount
	}
	return m0
}

type CarbonFootprint_DataQualityIndicators struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CompletenessDqr  float64                `protobuf:"fixed64,1,opt,name=completeness_dqr,json=completenessDQR"`
	xxx_hidden_CoveragePercent  float64                `protobuf:"fixed64,2,opt,name=coverage_percent,json=coveragePercent"`
	xxx_hidden_GeographicalDqr  float64                `protobuf:"fixed64,3,opt,name=geographical_dqr,json=geographicalDQR"`
	xxx_hidden_ReliabilityDqr   float64                `protobuf:"fixed64,4,opt,name=reliability_dqr,json=reliabilityDQR"`
	xxx_hidden_TechnologicalDqr float64                `protobuf:"fixed64,5,opt,name=technological_dqr,json=technologicalDQR"`
	xxx_hidden_TemporalDqr      float64                `protobuf:"fixed64,6,opt,name=temporal_dqr,json=temporalDQR"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CarbonFootprint_DataQualityIndicators) Reset() {
	*x = CarbonFootprint_DataQualityIndicators{}
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarbonFootprint_DataQualityIndicators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarbonFootprint_DataQualityIndicators) ProtoMessage() {}

func (x *CarbonFootprint_DataQualityIndicators) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CarbonFootprint_DataQualityIndicators) GetCompletenessDqr() float64 {
	if x != nil {
		return x.xxx_hidden_CompletenessDqr
	}
	return 0
}

func (x *CarbonFootprint_DataQualityIndicators) GetCoveragePercent() float64 {
	if x != nil {
		return x.xxx_hidden_CoveragePercent
	}
	return 0
}

func (x *CarbonFootprint_DataQualityIndicators) GetGeographicalDqr() float64 {
	if x != nil {
		return x.xxx_hidden_GeographicalDqr
	}
	return 0
}

func (x *CarbonFootprint_DataQualityIndicators) GetReliabilityDqr() float64 {
	if x != nil {
		return x.xxx_hidden_ReliabilityDqr
	}
	return 0
}

func (x *CarbonFootprint_DataQualityIndicators) GetTechnologicalDqr() float64 {
	if x != nil {
		return x.xxx_hidden_TechnologicalDqr
	}
	return 0
}

func (x *CarbonFootprint_DataQualityIndicators) GetTemporalDqr() float64 {
	if x != nil {
		return x.xxx_hidden_TemporalDqr
	}
	return 0
}

func (x *CarbonFootprint_DataQualityIndicators) SetCompletenessDqr(v float64) {
	x.xxx_hidden_CompletenessDqr = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *CarbonFootprint_DataQualityIndicators) SetCoveragePercent(v float64) {
	x.xxx_hidden_CoveragePercent = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *CarbonFootprint_DataQualityIndicators) SetGeographicalDqr(v float64) {
	x.xxx_hidden_GeographicalDqr = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *CarbonFootprint_DataQualityIndicators) SetReliabilityDqr(v float64) {
	x.xxx_hidden_ReliabilityDqr = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *CarbonFootprint_DataQualityIndicators) SetTechnologicalDqr(v float64) {
	x.xxx_hidden_TechnologicalDqr = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *CarbonFootprint_DataQualityIndicators) SetTemporalDqr(v float64) {
	x.xxx_hidden_TemporalDqr = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *CarbonFootprint_DataQualityIndicators) HasCompletenessDqr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CarbonFootprint_DataQualityIndicators) HasCoveragePercent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CarbonFootprint_DataQualityIndicators) HasGeographicalDqr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CarbonFootprint_DataQualityIndicators) HasReliabilityDqr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CarbonFootprint_DataQualityIndicators) HasTechnologicalDqr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CarbonFootprint_DataQualityIndicators) HasTemporalDqr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CarbonFootprint_DataQualityIndicators) ClearCompletenessDqr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CompletenessDqr = 0
}

func (x *CarbonFootprint_DataQualityIndicators) ClearCoveragePercent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CoveragePercent = 0
}

func (x *CarbonFootprint_DataQualityIndicators) ClearGeographicalDqr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_GeographicalDqr = 0
}

func (x *CarbonFootprint_DataQualityIndicators) ClearReliabilityDqr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ReliabilityDqr = 0
}

func (x *CarbonFootprint_DataQualityIndicators) ClearTechnologicalDqr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TechnologicalDqr = 0
}

func (x *CarbonFootprint_DataQualityIndicators) ClearTemporalDqr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_TemporalDqr = 0
}

type CarbonFootprint_DataQualityIndicators_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CompletenessDqr  *float64
	CoveragePercent  *float64
	GeographicalDqr  *float64
	ReliabilityDqr   *float64
	TechnologicalDqr *float64
	TemporalDqr      *float64
}

func (b0 CarbonFootprint_DataQualityIndicators_builder) Build() *CarbonFootprint_DataQualityIndicators {
	m0 := &CarbonFootprint_DataQualityIndicators{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CompletenessDqr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_CompletenessDqr = *b.CompletenessDqr
	}
	if b.CoveragePercent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_CoveragePercent = *b.CoveragePercent
	}
	if b.GeographicalDqr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_GeographicalDqr = *b.GeographicalDqr
	}
	if b.ReliabilityDqr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_ReliabilityDqr = *b.ReliabilityDqr
	}
	if b.TechnologicalDqr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_TechnologicalDqr = *b.TechnologicalDqr
	}
	if b.TemporalDqr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_TemporalDqr = *b.TemporalDqr
	}
	return m0
}

type CarbonFootprint_Assurance struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Assurance    bool                   `protobuf:"varint,1,opt,name=assurance"`
	xxx_hidden_Boundary     *string                `protobuf:"bytes,2,opt,name=boundary"`
	xxx_hidden_Comments     *string                `protobuf:"bytes,3,opt,name=comments"`
	xxx_hidden_CompletedAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt"`
	xxx_hidden_Coverage     *string                `protobuf:"bytes,5,opt,name=coverage"`
	xxx_hidden_Level        *string                `protobuf:"bytes,6,opt,name=level"`
	xxx_hidden_ProviderName *string                `protobuf:"bytes,7,opt,name=provider_name,json=providerName"`
	xxx_hidden_StandardName *string                `protobuf:"bytes,8,opt,name=standard_name,json=standardName"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CarbonFootprint_Assurance) Reset() {
	*x = CarbonFootprint_Assurance{}
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarbonFootprint_Assurance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarbonFootprint_Assurance) ProtoMessage() {}

func (x *CarbonFootprint_Assurance) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CarbonFootprint_Assurance) GetAssurance() bool {
	if x != nil {
		return x.xxx_hidden_Assurance
	}
	return false
}

func (x *CarbonFootprint_Assurance) GetBoundary() string {
	if x != nil {
		if x.xxx_hidden_Boundary != nil {
			return *x.xxx_hidden_Boundary
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_Assurance) GetComments() string {
	if x != nil {
		if x.xxx_hidden_Comments != nil {
			return *x.xxx_hidden_Comments
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_Assurance) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CompletedAt
	}
	return nil
}

func (x *CarbonFootprint_Assurance) GetCoverage() string {
	if x != nil {
		if x.xxx_hidden_Coverage != nil {
			return *x.xxx_hidden_Coverage
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_Assurance) GetLevel() string {
	if x != nil {
		if x.xxx_hidden_Level != nil {
			return *x.xxx_hidden_Level
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_Assurance) GetProviderName() string {
	if x != nil {
		if x.xxx_hidden_ProviderName != nil {
			return *x.xxx_hidden_ProviderName
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_Assurance) GetStandardName() string {
	if x != nil {
		if x.xxx_hidden_StandardName != nil {
			return *x.xxx_hidden_StandardName
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_Assurance) SetAssurance(v bool) {
	x.xxx_hidden_Assurance = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *CarbonFootprint_Assurance) SetBoundary(v string) {
	x.xxx_hidden_Boundary = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *CarbonFootprint_Assurance) SetComments(v string) {
	x.xxx_hidden_Comments = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *CarbonFootprint_Assurance) SetCompletedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CompletedAt = v
}

func (x *CarbonFootprint_Assurance) SetCoverage(v string) {
	x.xxx_hidden_Coverage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *CarbonFootprint_Assurance) SetLevel(v string) {
	x.xxx_hidden_Level = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *CarbonFootprint_Assurance) SetProviderName(v string) {
	x.xxx_hidden_ProviderName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *CarbonFootprint_Assurance) SetStandardName(v string) {
	x.xxx_hidden_StandardName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *CarbonFootprint_Assurance) HasAssurance() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CarbonFootprint_Assurance) HasBoundary() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CarbonFootprint_Assurance) HasComments() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CarbonFootprint_Assurance) HasCompletedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CompletedAt != nil
}

func (x *CarbonFootprint_Assurance) HasCoverage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CarbonFootprint_Assurance) HasLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CarbonFootprint_Assurance) HasProviderName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *CarbonFootprint_Assurance) HasStandardName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *CarbonFootprint_Assurance) ClearAssurance() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Assurance = false
}

func (x *CarbonFootprint_Assurance) ClearBoundary() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Boundary = nil
}

func (x *CarbonFootprint_Assurance) ClearComments() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Comments = nil
}

func (x *CarbonFootprint_Assurance) ClearCompletedAt() {
	x.xxx_hidden_CompletedAt = nil
}

func (x *CarbonFootprint_Assurance) ClearCoverage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Coverage = nil
}

func (x *CarbonFootprint_Assurance) ClearLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Level = nil
}

func (x *CarbonFootprint_Assurance) ClearProviderName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ProviderName = nil
}

func (x *CarbonFootprint_Assurance) ClearStandardName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_StandardName = nil
}

type CarbonFootprint_Assurance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Assurance    *bool
	Boundary     *string
	Comments     *string
	CompletedAt  *timestamppb.Timestamp
	Coverage     *string
	Level        *string
	ProviderName *string
	StandardName *string
}

func (b0 CarbonFootprint_Assurance_builder) Build() *CarbonFootprint_Assurance {
	m0 := &CarbonFootprint_Assurance{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Assurance != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Assurance = *b.Assurance
	}
	if b.Boundary != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Boundary = b.Boundary
	}
	if b.Comments != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Comments = b.Comments
	}
	x.xxx_hidden_CompletedAt = b.CompletedAt
	if b.Coverage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Coverage = b.Coverage
	}
	if b.Level != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Level = b.Level
	}
	if b.ProviderName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_ProviderName = b.ProviderName
	}
	if b.StandardName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_StandardName = b.StandardName
	}
	return m0
}

type CarbonFootprint_ProductOrSectorSpecificRule struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Operator          *string                `protobuf:"bytes,1,opt,name=operator"`
	xxx_hidden_OtherOperatorName *string                `protobuf:"bytes,2,opt,name=other_operator_name,json=otherOperatorName"`
	xxx_hidden_RuleNames         []string               `protobuf:"bytes,3,rep,name=rule_names,json=ruleNames"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) Reset() {
	*x = CarbonFootprint_ProductOrSectorSpecificRule{}
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarbonFootprint_ProductOrSectorSpecificRule) ProtoMessage() {}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) GetOperator() string {
	if x != nil {
		if x.xxx_hidden_Operator != nil {
			return *x.xxx_hidden_Operator
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) GetOtherOperatorName() string {
	if x != nil {
		if x.xxx_hidden_OtherOperatorName != nil {
			return *x.xxx_hidden_OtherOperatorName
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) GetRuleNames() []string {
	if x != nil {
		return x.xxx_hidden_RuleNames
	}
	return nil
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) SetOperator(v string) {
	x.xxx_hidden_Operator = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) SetOtherOperatorName(v string) {
	x.xxx_hidden_OtherOperatorName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) SetRuleNames(v []string) {
	x.xxx_hidden_RuleNames = v
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) HasOperator() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) HasOtherOperatorName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) ClearOperator() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Operator = nil
}

func (x *CarbonFootprint_ProductOrSectorSpecificRule) ClearOtherOperatorName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OtherOperatorName = nil
}

type CarbonFootprint_ProductOrSectorSpecificRule_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Operator          *string
	OtherOperatorName *string
	RuleNames         []string
}

func (b0 CarbonFootprint_ProductOrSectorSpecificRule_builder) Build() *CarbonFootprint_ProductOrSectorSpecificRule {
	m0 := &CarbonFootprint_ProductOrSectorSpecificRule{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Operator != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Operator = b.Operator
	}
	if b.OtherOperatorName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_OtherOperatorName = b.OtherOperatorName
	}
	x.xxx_hidden_RuleNames = b.RuleNames
	return m0
}

type CarbonFootprint_EmissionFactorDS struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Version     *string                `protobuf:"bytes,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CarbonFootprint_EmissionFactorDS) Reset() {
	*x = CarbonFootprint_EmissionFactorDS{}
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarbonFootprint_EmissionFactorDS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarbonFootprint_EmissionFactorDS) ProtoMessage() {}

func (x *CarbonFootprint_EmissionFactorDS) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CarbonFootprint_EmissionFactorDS) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_EmissionFactorDS) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *CarbonFootprint_EmissionFactorDS) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CarbonFootprint_EmissionFactorDS) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CarbonFootprint_EmissionFactorDS) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CarbonFootprint_EmissionFactorDS) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CarbonFootprint_EmissionFactorDS) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *CarbonFootprint_EmissionFactorDS) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = nil
}

type CarbonFootprint_EmissionFactorDS_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name    *string
	Version *string
}

func (b0 CarbonFootprint_EmissionFactorDS_builder) Build() *CarbonFootprint_EmissionFactorDS {
	m0 := &CarbonFootprint_EmissionFactorDS{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = b.Version
	}
	return m0
}

var File_wayplatform_connect_ileap_v1_carbon_footprint_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_carbon_footprint_proto_rawDesc = "" +
	"\n" +
	"3wayplatform/connect/ileap/v1/carbon_footprint.proto\x12\x1cwayplatform.connect.ileap.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x18\n" +
	"\x0fCarbonFootprint\x124\n" +
	"\x16aircraft_ghg_emissions\x18\x01 \x01(\tR\x14aircraftGhgEmissions\x12@\n" +
	"\x1callocation_rules_description\x18\x02 \x01(\tR\x1aallocationRulesDescription\x12U\n" +
	"\tassurance\x18\x03 \x01(\v27.wayplatform.connect.ileap.v1.CarbonFootprint.AssuranceR\tassurance\x12F\n" +
	"\x1fbiogenic_accounting_methodology\x18\x04 \x01(\tR\x1dbiogenicAccountingMethodology\x126\n" +
	"\x17biogenic_carbon_content\x18\x05 \x01(\tR\x15biogenicCarbonContent\x12<\n" +
	"\x1abiogenic_carbon_withdrawal\x18\x06 \x01(\tR\x18biogenicCarbonWithdrawal\x12D\n" +
	"\x1eboundary_processes_description\x18\a \x01(\tR\x1cboundaryProcessesDescription\x129\n" +
	"\x18characterization_factors\x18\b \x01(\tR\x17characterizationFactors\x12A\n" +
	"\x1dcross_sectoral_standards_used\x18\t \x03(\tR\x1acrossSectoralStandardsUsed\x12-\n" +
	"\x13d_luc_ghg_emissions\x18\n" +
	" \x01(\tR\x10dLucGhgEmissions\x12#\n" +
	"\rdeclared_unit\x18\v \x01(\tR\fdeclaredUnit\x12U\n" +
	"\x03dqi\x18\f \x01(\v2C.wayplatform.connect.ileap.v1.CarbonFootprint.DataQualityIndicatorsR\x03dqi\x12D\n" +
	"\x1eexempted_emissions_description\x18\r \x01(\tR\x1cexemptedEmissionsDescription\x12<\n" +
	"\x1aexempted_emissions_percent\x18\x0e \x01(\x01R\x18exemptedEmissionsPercent\x122\n" +
	"\x15fossil_carbon_content\x18\x0f \x01(\tR\x13fossilCarbonContent\x120\n" +
	"\x14fossil_ghg_emissions\x18\x10 \x01(\tR\x12fossilGhgEmissions\x12+\n" +
	"\x11geography_country\x18\x11 \x01(\tR\x10geographyCountry\x12B\n" +
	"\x1dgeography_country_subdivision\x18\x12 \x01(\tR\x1bgeographyCountrySubdivision\x12A\n" +
	"\x1dgeography_region_or_subregion\x18\x13 \x01(\tR\x1ageographyRegionOrSubregion\x12-\n" +
	"\x13i_luc_ghg_emissions\x18\x14 \x01(\tR\x10iLucGhgEmissions\x12Q\n" +
	"%ipcc_characterization_factors_sources\x18\x15 \x03(\tR\"ipccCharacterizationFactorsSources\x12A\n" +
	"\x1dland_management_ghg_emissions\x18\x16 \x01(\tR\x1alandManagementGhgEmissions\x12?\n" +
	"\x1cother_biogenic_ghg_emissions\x18\x17 \x01(\tR\x19otherBiogenicGhgEmissions\x125\n" +
	"\x17p_cf_excluding_biogenic\x18\x18 \x01(\tR\x14pCfExcludingBiogenic\x125\n" +
	"\x17p_cf_including_biogenic\x18\x19 \x01(\tR\x14pCfIncludingBiogenic\x12@\n" +
	"\x1cpackaging_emissions_included\x18\x1a \x01(\bR\x1apackagingEmissionsIncluded\x126\n" +
	"\x17packaging_ghg_emissions\x18\x1b \x01(\tR\x15packagingGhgEmissions\x12,\n" +
	"\x12primary_data_share\x18\x1c \x01(\x01R\x10primaryDataShare\x12\x91\x01\n" +
	" product_or_sector_specific_rules\x18\x1d \x03(\v2I.wayplatform.connect.ileap.v1.CarbonFootprint.ProductOrSectorSpecificRuleR\x1cproductOrSectorSpecificRules\x12L\n" +
	"\x14reference_period_end\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\x12referencePeriodEnd\x12P\n" +
	"\x16reference_period_start\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\x14referencePeriodStart\x12\x89\x01\n" +
	"!secondary_emission_factor_sources\x18  \x03(\v2>.wayplatform.connect.ileap.v1.CarbonFootprint.EmissionFactorDSR\x1esecondaryEmissionFactorSources\x12L\n" +
	"\"uncertainty_assessment_description\x18! \x01(\tR uncertaintyAssessmentDescription\x124\n" +
	"\x16unitary_product_amount\x18\" \x01(\tR\x14unitaryProductAmount\x1a\x91\x02\n" +
	"\x15DataQualityIndicators\x12)\n" +
	"\x10completeness_dqr\x18\x01 \x01(\x01R\x0fcompletenessDQR\x12)\n" +
	"\x10coverage_percent\x18\x02 \x01(\x01R\x0fcoveragePercent\x12)\n" +
	"\x10geographical_dqr\x18\x03 \x01(\x01R\x0fgeographicalDQR\x12'\n" +
	"\x0freliability_dqr\x18\x04 \x01(\x01R\x0ereliabilityDQR\x12+\n" +
	"\x11technological_dqr\x18\x05 \x01(\x01R\x10technologicalDQR\x12!\n" +
	"\ftemporal_dqr\x18\x06 \x01(\x01R\vtemporalDQR\x1a\x9c\x02\n" +
	"\tAssurance\x12\x1c\n" +
	"\tassurance\x18\x01 \x01(\bR\tassurance\x12\x1a\n" +
	"\bboundary\x18\x02 \x01(\tR\bboundary\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\tR\bcomments\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1a\n" +
	"\bcoverage\x18\x05 \x01(\tR\bcoverage\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\x12#\n" +
	"\rprovider_name\x18\a \x01(\tR\fproviderName\x12#\n" +
	"\rstandard_name\x18\b \x01(\tR\fstandardName\x1a\x88\x01\n" +
	"\x1bProductOrSectorSpecificRule\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12.\n" +
	"\x13other_operator_name\x18\x02 \x01(\tR\x11otherOperatorName\x12\x1d\n" +
	"\n" +
	"rule_names\x18\x03 \x03(\tR\truleNames\x1a@\n" +
	"\x10EmissionFactorDS\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversionB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wayplatform_connect_ileap_v1_carbon_footprint_proto_goTypes = []any{
	(*CarbonFootprint)(nil),                             // 0: wayplatform.connect.ileap.v1.CarbonFootprint
	(*CarbonFootprint_DataQualityIndicators)(nil),       // 1: wayplatform.connect.ileap.v1.CarbonFootprint.DataQualityIndicators
	(*CarbonFootprint_Assurance)(nil),                   // 2: wayplatform.connect.ileap.v1.CarbonFootprint.Assurance
	(*CarbonFootprint_ProductOrSectorSpecificRule)(nil), // 3: wayplatform.connect.ileap.v1.CarbonFootprint.ProductOrSectorSpecificRule
	(*CarbonFootprint_EmissionFactorDS)(nil),            // 4: wayplatform.connect.ileap.v1.CarbonFootprint.EmissionFactorDS
	(*timestamppb.Timestamp)(nil),                       // 5: google.protobuf.Timestamp
}
var file_wayplatform_connect_ileap_v1_carbon_footprint_proto_depIdxs = []int32{
	2, // 0: wayplatform.connect.ileap.v1.CarbonFootprint.assurance:type_name -> wayplatform.connect.ileap.v1.CarbonFootprint.Assurance
	1, // 1: wayplatform.connect.ileap.v1.CarbonFootprint.dqi:type_name -> wayplatform.connect.ileap.v1.CarbonFootprint.DataQualityIndicators
	3, // 2: wayplatform.connect.ileap.v1.CarbonFootprint.product_or_sector_specific_rules:type_name -> wayplatform.connect.ileap.v1.CarbonFootprint.ProductOrSectorSpecificRule
	5, // 3: wayplatform.connect.ileap.v1.CarbonFootprint.reference_period_end:type_name -> google.protobuf.Timestamp
	5, // 4: wayplatform.connect.ileap.v1.CarbonFootprint.reference_period_start:type_name -> google.protobuf.Timestamp
	4, // 5: wayplatform.connect.ileap.v1.CarbonFootprint.secondary_emission_factor_sources:type_name -> wayplatform.connect.ileap.v1.CarbonFootprint.EmissionFactorDS
	5, // 6: wayplatform.connect.ileap.v1.CarbonFootprint.Assurance.completed_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_carbon_footprint_proto_init() }
func file_wayplatform_connect_ileap_v1_carbon_footprint_proto_init() {
	if File_wayplatform_connect_ileap_v1_carbon_footprint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_carbon_footprint_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_carbon_footprint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_carbon_footprint_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_carbon_footprint_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_carbon_footprint_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_carbon_footprint_proto = out.File
	file_wayplatform_connect_ileap_v1_carbon_footprint_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_carbon_footprint_proto_depIdxs = nil
}
