// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/data_model_extension.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataModelExtension is the PACT extension envelope for iLEAP extension data.
type DataModelExtension struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SpecVersion   *string                `protobuf:"bytes,1,opt,name=spec_version,json=specVersion"`
	xxx_hidden_DataSchema    *string                `protobuf:"bytes,2,opt,name=data_schema,json=dataSchema"`
	xxx_hidden_Documentation *string                `protobuf:"bytes,3,opt,name=documentation"`
	xxx_hidden_Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DataModelExtension) Reset() {
	*x = DataModelExtension{}
	mi := &file_wayplatform_connect_ileap_v1_data_model_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataModelExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataModelExtension) ProtoMessage() {}

func (x *DataModelExtension) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_data_model_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataModelExtension) GetSpecVersion() string {
	if x != nil {
		if x.xxx_hidden_SpecVersion != nil {
			return *x.xxx_hidden_SpecVersion
		}
		return ""
	}
	return ""
}

func (x *DataModelExtension) GetDataSchema() string {
	if x != nil {
		if x.xxx_hidden_DataSchema != nil {
			return *x.xxx_hidden_DataSchema
		}
		return ""
	}
	return ""
}

func (x *DataModelExtension) GetDocumentation() string {
	if x != nil {
		if x.xxx_hidden_Documentation != nil {
			return *x.xxx_hidden_Documentation
		}
		return ""
	}
	return ""
}

func (x *DataModelExtension) GetData() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *DataModelExtension) SetSpecVersion(v string) {
	x.xxx_hidden_SpecVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DataModelExtension) SetDataSchema(v string) {
	x.xxx_hidden_DataSchema = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DataModelExtension) SetDocumentation(v string) {
	x.xxx_hidden_Documentation = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *DataModelExtension) SetData(v *structpb.Struct) {
	x.xxx_hidden_Data = v
}

func (x *DataModelExtension) HasSpecVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DataModelExtension) HasDataSchema() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DataModelExtension) HasDocumentation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DataModelExtension) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *DataModelExtension) ClearSpecVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SpecVersion = nil
}

func (x *DataModelExtension) ClearDataSchema() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DataSchema = nil
}

func (x *DataModelExtension) ClearDocumentation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Documentation = nil
}

func (x *DataModelExtension) ClearData() {
	x.xxx_hidden_Data = nil
}

type DataModelExtension_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SpecVersion   *string
	DataSchema    *string
	Documentation *string
	Data          *structpb.Struct
}

func (b0 DataModelExtension_builder) Build() *DataModelExtension {
	m0 := &DataModelExtension{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SpecVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_SpecVersion = b.SpecVersion
	}
	if b.DataSchema != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_DataSchema = b.DataSchema
	}
	if b.Documentation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Documentation = b.Documentation
	}
	x.xxx_hidden_Data = b.Data
	return m0
}

var File_wayplatform_connect_ileap_v1_data_model_extension_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_data_model_extension_proto_rawDesc = "" +
	"\n" +
	"7wayplatform/connect/ileap/v1/data_model_extension.proto\x12\x1cwayplatform.connect.ileap.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xab\x01\n" +
	"\x12DataModelExtension\x12!\n" +
	"\fspec_version\x18\x01 \x01(\tR\vspecVersion\x12\x1f\n" +
	"\vdata_schema\x18\x02 \x01(\tR\n" +
	"dataSchema\x12$\n" +
	"\rdocumentation\x18\x03 \x01(\tR\rdocumentation\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04dataB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_data_model_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_data_model_extension_proto_goTypes = []any{
	(*DataModelExtension)(nil), // 0: wayplatform.connect.ileap.v1.DataModelExtension
	(*structpb.Struct)(nil),    // 1: google.protobuf.Struct
}
var file_wayplatform_connect_ileap_v1_data_model_extension_proto_depIdxs = []int32{
	1, // 0: wayplatform.connect.ileap.v1.DataModelExtension.data:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_data_model_extension_proto_init() }
func file_wayplatform_connect_ileap_v1_data_model_extension_proto_init() {
	if File_wayplatform_connect_ileap_v1_data_model_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_data_model_extension_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_data_model_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_data_model_extension_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_data_model_extension_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_data_model_extension_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_data_model_extension_proto = out.File
	file_wayplatform_connect_ileap_v1_data_model_extension_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_data_model_extension_proto_depIdxs = nil
}
