// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/energy_carrier.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnergyCarrier represents an energy carrier with emission factors.
type EnergyCarrier struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EnergyCarrier         *string                `protobuf:"bytes,1,opt,name=energy_carrier,json=energyCarrier"`
	xxx_hidden_EnergyConsumptionUnit *string                `protobuf:"bytes,2,opt,name=energy_consumption_unit,json=energyConsumptionUnit"`
	xxx_hidden_EmissionFactorTtw     *string                `protobuf:"bytes,3,opt,name=emission_factor_ttw,json=emissionFactorTTW"`
	xxx_hidden_EmissionFactorWtw     *string                `protobuf:"bytes,4,opt,name=emission_factor_wtw,json=emissionFactorWTW"`
	xxx_hidden_RelativeShare         *string                `protobuf:"bytes,5,opt,name=relative_share,json=relativeShare"`
	xxx_hidden_Feedstocks            *[]*Feedstock          `protobuf:"bytes,6,rep,name=feedstocks"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *EnergyCarrier) Reset() {
	*x = EnergyCarrier{}
	mi := &file_wayplatform_connect_ileap_v1_energy_carrier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnergyCarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyCarrier) ProtoMessage() {}

func (x *EnergyCarrier) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_energy_carrier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnergyCarrier) GetEnergyCarrier() string {
	if x != nil {
		if x.xxx_hidden_EnergyCarrier != nil {
			return *x.xxx_hidden_EnergyCarrier
		}
		return ""
	}
	return ""
}

func (x *EnergyCarrier) GetEnergyConsumptionUnit() string {
	if x != nil {
		if x.xxx_hidden_EnergyConsumptionUnit != nil {
			return *x.xxx_hidden_EnergyConsumptionUnit
		}
		return ""
	}
	return ""
}

func (x *EnergyCarrier) GetEmissionFactorTtw() string {
	if x != nil {
		if x.xxx_hidden_EmissionFactorTtw != nil {
			return *x.xxx_hidden_EmissionFactorTtw
		}
		return ""
	}
	return ""
}

func (x *EnergyCarrier) GetEmissionFactorWtw() string {
	if x != nil {
		if x.xxx_hidden_EmissionFactorWtw != nil {
			return *x.xxx_hidden_EmissionFactorWtw
		}
		return ""
	}
	return ""
}

func (x *EnergyCarrier) GetRelativeShare() string {
	if x != nil {
		if x.xxx_hidden_RelativeShare != nil {
			return *x.xxx_hidden_RelativeShare
		}
		return ""
	}
	return ""
}

func (x *EnergyCarrier) GetFeedstocks() []*Feedstock {
	if x != nil {
		if x.xxx_hidden_Feedstocks != nil {
			return *x.xxx_hidden_Feedstocks
		}
	}
	return nil
}

func (x *EnergyCarrier) SetEnergyCarrier(v string) {
	x.xxx_hidden_EnergyCarrier = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *EnergyCarrier) SetEnergyConsumptionUnit(v string) {
	x.xxx_hidden_EnergyConsumptionUnit = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *EnergyCarrier) SetEmissionFactorTtw(v string) {
	x.xxx_hidden_EmissionFactorTtw = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *EnergyCarrier) SetEmissionFactorWtw(v string) {
	x.xxx_hidden_EmissionFactorWtw = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *EnergyCarrier) SetRelativeShare(v string) {
	x.xxx_hidden_RelativeShare = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *EnergyCarrier) SetFeedstocks(v []*Feedstock) {
	x.xxx_hidden_Feedstocks = &v
}

func (x *EnergyCarrier) HasEnergyCarrier() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EnergyCarrier) HasEnergyConsumptionUnit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EnergyCarrier) HasEmissionFactorTtw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EnergyCarrier) HasEmissionFactorWtw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *EnergyCarrier) HasRelativeShare() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *EnergyCarrier) ClearEnergyCarrier() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EnergyCarrier = nil
}

func (x *EnergyCarrier) ClearEnergyConsumptionUnit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EnergyConsumptionUnit = nil
}

func (x *EnergyCarrier) ClearEmissionFactorTtw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EmissionFactorTtw = nil
}

func (x *EnergyCarrier) ClearEmissionFactorWtw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_EmissionFactorWtw = nil
}

func (x *EnergyCarrier) ClearRelativeShare() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_RelativeShare = nil
}

type EnergyCarrier_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EnergyCarrier         *string
	EnergyConsumptionUnit *string
	EmissionFactorTtw     *string
	EmissionFactorWtw     *string
	RelativeShare         *string
	Feedstocks            []*Feedstock
}

func (b0 EnergyCarrier_builder) Build() *EnergyCarrier {
	m0 := &EnergyCarrier{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EnergyCarrier != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_EnergyCarrier = b.EnergyCarrier
	}
	if b.EnergyConsumptionUnit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_EnergyConsumptionUnit = b.EnergyConsumptionUnit
	}
	if b.EmissionFactorTtw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_EmissionFactorTtw = b.EmissionFactorTtw
	}
	if b.EmissionFactorWtw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_EmissionFactorWtw = b.EmissionFactorWtw
	}
	if b.RelativeShare != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_RelativeShare = b.RelativeShare
	}
	x.xxx_hidden_Feedstocks = &b.Feedstocks
	return m0
}

var File_wayplatform_connect_ileap_v1_energy_carrier_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_energy_carrier_proto_rawDesc = "" +
	"\n" +
	"1wayplatform/connect/ileap/v1/energy_carrier.proto\x12\x1cwayplatform.connect.ileap.v1\x1a,wayplatform/connect/ileap/v1/feedstock.proto\"\xbe\x02\n" +
	"\rEnergyCarrier\x12%\n" +
	"\x0eenergy_carrier\x18\x01 \x01(\tR\renergyCarrier\x126\n" +
	"\x17energy_consumption_unit\x18\x02 \x01(\tR\x15energyConsumptionUnit\x12.\n" +
	"\x13emission_factor_ttw\x18\x03 \x01(\tR\x11emissionFactorTTW\x12.\n" +
	"\x13emission_factor_wtw\x18\x04 \x01(\tR\x11emissionFactorWTW\x12%\n" +
	"\x0erelative_share\x18\x05 \x01(\tR\rrelativeShare\x12G\n" +
	"\n" +
	"feedstocks\x18\x06 \x03(\v2'.wayplatform.connect.ileap.v1.FeedstockR\n" +
	"feedstocksB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_energy_carrier_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_energy_carrier_proto_goTypes = []any{
	(*EnergyCarrier)(nil), // 0: wayplatform.connect.ileap.v1.EnergyCarrier
	(*Feedstock)(nil),     // 1: wayplatform.connect.ileap.v1.Feedstock
}
var file_wayplatform_connect_ileap_v1_energy_carrier_proto_depIdxs = []int32{
	1, // 0: wayplatform.connect.ileap.v1.EnergyCarrier.feedstocks:type_name -> wayplatform.connect.ileap.v1.Feedstock
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_energy_carrier_proto_init() }
func file_wayplatform_connect_ileap_v1_energy_carrier_proto_init() {
	if File_wayplatform_connect_ileap_v1_energy_carrier_proto != nil {
		return
	}
	file_wayplatform_connect_ileap_v1_feedstock_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_energy_carrier_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_energy_carrier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_energy_carrier_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_energy_carrier_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_energy_carrier_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_energy_carrier_proto = out.File
	file_wayplatform_connect_ileap_v1_energy_carrier_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_energy_carrier_proto_depIdxs = nil
}
