// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/feedstock.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Feedstock represents feedstock information for energy carriers.
type Feedstock struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Feedstock           *string                `protobuf:"bytes,1,opt,name=feedstock"`
	xxx_hidden_FeedstockPercentage *string                `protobuf:"bytes,2,opt,name=feedstock_percentage,json=feedstockPercentage"`
	xxx_hidden_RegionProvenance    *string                `protobuf:"bytes,3,opt,name=region_provenance,json=regionProvenance"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Feedstock) Reset() {
	*x = Feedstock{}
	mi := &file_wayplatform_connect_ileap_v1_feedstock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedstock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedstock) ProtoMessage() {}

func (x *Feedstock) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_feedstock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Feedstock) GetFeedstock() string {
	if x != nil {
		if x.xxx_hidden_Feedstock != nil {
			return *x.xxx_hidden_Feedstock
		}
		return ""
	}
	return ""
}

func (x *Feedstock) GetFeedstockPercentage() string {
	if x != nil {
		if x.xxx_hidden_FeedstockPercentage != nil {
			return *x.xxx_hidden_FeedstockPercentage
		}
		return ""
	}
	return ""
}

func (x *Feedstock) GetRegionProvenance() string {
	if x != nil {
		if x.xxx_hidden_RegionProvenance != nil {
			return *x.xxx_hidden_RegionProvenance
		}
		return ""
	}
	return ""
}

func (x *Feedstock) SetFeedstock(v string) {
	x.xxx_hidden_Feedstock = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Feedstock) SetFeedstockPercentage(v string) {
	x.xxx_hidden_FeedstockPercentage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Feedstock) SetRegionProvenance(v string) {
	x.xxx_hidden_RegionProvenance = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Feedstock) HasFeedstock() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Feedstock) HasFeedstockPercentage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Feedstock) HasRegionProvenance() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Feedstock) ClearFeedstock() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Feedstock = nil
}

func (x *Feedstock) ClearFeedstockPercentage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_FeedstockPercentage = nil
}

func (x *Feedstock) ClearRegionProvenance() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RegionProvenance = nil
}

type Feedstock_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Feedstock           *string
	FeedstockPercentage *string
	RegionProvenance    *string
}

func (b0 Feedstock_builder) Build() *Feedstock {
	m0 := &Feedstock{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Feedstock != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Feedstock = b.Feedstock
	}
	if b.FeedstockPercentage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_FeedstockPercentage = b.FeedstockPercentage
	}
	if b.RegionProvenance != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_RegionProvenance = b.RegionProvenance
	}
	return m0
}

var File_wayplatform_connect_ileap_v1_feedstock_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_feedstock_proto_rawDesc = "" +
	"\n" +
	",wayplatform/connect/ileap/v1/feedstock.proto\x12\x1cwayplatform.connect.ileap.v1\"\x89\x01\n" +
	"\tFeedstock\x12\x1c\n" +
	"\tfeedstock\x18\x01 \x01(\tR\tfeedstock\x121\n" +
	"\x14feedstock_percentage\x18\x02 \x01(\tR\x13feedstockPercentage\x12+\n" +
	"\x11region_provenance\x18\x03 \x01(\tR\x10regionProvenanceB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_feedstock_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_feedstock_proto_goTypes = []any{
	(*Feedstock)(nil), // 0: wayplatform.connect.ileap.v1.Feedstock
}
var file_wayplatform_connect_ileap_v1_feedstock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_feedstock_proto_init() }
func file_wayplatform_connect_ileap_v1_feedstock_proto_init() {
	if File_wayplatform_connect_ileap_v1_feedstock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_feedstock_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_feedstock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_feedstock_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_feedstock_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_feedstock_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_feedstock_proto = out.File
	file_wayplatform_connect_ileap_v1_feedstock_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_feedstock_proto_depIdxs = nil
}
