// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/glec_distance.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GlecDistance represents distance values per GLEC Framework.
type GlecDistance struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Actual      *string                `protobuf:"bytes,1,opt,name=actual"`
	xxx_hidden_Glec        *string                `protobuf:"bytes,2,opt,name=glec,json=gcd"`
	xxx_hidden_Sfd         *string                `protobuf:"bytes,3,opt,name=sfd"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GlecDistance) Reset() {
	*x = GlecDistance{}
	mi := &file_wayplatform_connect_ileap_v1_glec_distance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlecDistance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlecDistance) ProtoMessage() {}

func (x *GlecDistance) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_glec_distance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GlecDistance) GetActual() string {
	if x != nil {
		if x.xxx_hidden_Actual != nil {
			return *x.xxx_hidden_Actual
		}
		return ""
	}
	return ""
}

func (x *GlecDistance) GetGlec() string {
	if x != nil {
		if x.xxx_hidden_Glec != nil {
			return *x.xxx_hidden_Glec
		}
		return ""
	}
	return ""
}

func (x *GlecDistance) GetSfd() string {
	if x != nil {
		if x.xxx_hidden_Sfd != nil {
			return *x.xxx_hidden_Sfd
		}
		return ""
	}
	return ""
}

func (x *GlecDistance) SetActual(v string) {
	x.xxx_hidden_Actual = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *GlecDistance) SetGlec(v string) {
	x.xxx_hidden_Glec = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *GlecDistance) SetSfd(v string) {
	x.xxx_hidden_Sfd = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *GlecDistance) HasActual() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GlecDistance) HasGlec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GlecDistance) HasSfd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GlecDistance) ClearActual() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Actual = nil
}

func (x *GlecDistance) ClearGlec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Glec = nil
}

func (x *GlecDistance) ClearSfd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Sfd = nil
}

type GlecDistance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Actual *string
	Glec   *string
	Sfd    *string
}

func (b0 GlecDistance_builder) Build() *GlecDistance {
	m0 := &GlecDistance{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Actual != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Actual = b.Actual
	}
	if b.Glec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Glec = b.Glec
	}
	if b.Sfd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Sfd = b.Sfd
	}
	return m0
}

var File_wayplatform_connect_ileap_v1_glec_distance_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_glec_distance_proto_rawDesc = "" +
	"\n" +
	"0wayplatform/connect/ileap/v1/glec_distance.proto\x12\x1cwayplatform.connect.ileap.v1\"K\n" +
	"\fGlecDistance\x12\x16\n" +
	"\x06actual\x18\x01 \x01(\tR\x06actual\x12\x11\n" +
	"\x04glec\x18\x02 \x01(\tR\x03gcd\x12\x10\n" +
	"\x03sfd\x18\x03 \x01(\tR\x03sfdB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_glec_distance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_glec_distance_proto_goTypes = []any{
	(*GlecDistance)(nil), // 0: wayplatform.connect.ileap.v1.GlecDistance
}
var file_wayplatform_connect_ileap_v1_glec_distance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_glec_distance_proto_init() }
func file_wayplatform_connect_ileap_v1_glec_distance_proto_init() {
	if File_wayplatform_connect_ileap_v1_glec_distance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_glec_distance_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_glec_distance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_glec_distance_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_glec_distance_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_glec_distance_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_glec_distance_proto = out.File
	file_wayplatform_connect_ileap_v1_glec_distance_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_glec_distance_proto_depIdxs = nil
}
