// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/hoc.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HOC (Hub Operation Category) is the iLEAP extension for hub operation footprints.
type HOC struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HocId                   *string                `protobuf:"bytes,1,opt,name=hoc_id,json=hocId"`
	xxx_hidden_HubType                 *string                `protobuf:"bytes,2,opt,name=hub_type,json=hubType"`
	xxx_hidden_HubActivityUnit         *string                `protobuf:"bytes,3,opt,name=hub_activity_unit,json=hubActivityUnit"`
	xxx_hidden_InboundTransportMode    *string                `protobuf:"bytes,4,opt,name=inbound_transport_mode,json=inboundTransportMode"`
	xxx_hidden_OutboundTransportMode   *string                `protobuf:"bytes,5,opt,name=outbound_transport_mode,json=outboundTransportMode"`
	xxx_hidden_TemperatureControl      *string                `protobuf:"bytes,6,opt,name=temperature_control,json=temperatureControl"`
	xxx_hidden_Co2EIntensityTtw        *string                `protobuf:"bytes,7,opt,name=co2e_intensity_ttw,json=co2eIntensityTTW"`
	xxx_hidden_Co2EIntensityWtw        *string                `protobuf:"bytes,8,opt,name=co2e_intensity_wtw,json=co2eIntensityWTW"`
	xxx_hidden_Co2EIntensityThroughput *string                `protobuf:"bytes,9,opt,name=co2e_intensity_throughput,json=co2eIntensityThroughput"`
	xxx_hidden_EnergyCarriers          *[]*EnergyCarrier      `protobuf:"bytes,10,rep,name=energy_carriers,json=energyCarriers"`
	xxx_hidden_IsVerified              bool                   `protobuf:"varint,11,opt,name=is_verified,json=isVerified"`
	xxx_hidden_IsAccredited            bool                   `protobuf:"varint,12,opt,name=is_accredited,json=isAccredited"`
	XXX_raceDetectHookData             protoimpl.RaceDetectHookData
	XXX_presence                       [1]uint32
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *HOC) Reset() {
	*x = HOC{}
	mi := &file_wayplatform_connect_ileap_v1_hoc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HOC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HOC) ProtoMessage() {}

func (x *HOC) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_hoc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HOC) GetHocId() string {
	if x != nil {
		if x.xxx_hidden_HocId != nil {
			return *x.xxx_hidden_HocId
		}
		return ""
	}
	return ""
}

func (x *HOC) GetHubType() string {
	if x != nil {
		if x.xxx_hidden_HubType != nil {
			return *x.xxx_hidden_HubType
		}
		return ""
	}
	return ""
}

func (x *HOC) GetHubActivityUnit() string {
	if x != nil {
		if x.xxx_hidden_HubActivityUnit != nil {
			return *x.xxx_hidden_HubActivityUnit
		}
		return ""
	}
	return ""
}

func (x *HOC) GetInboundTransportMode() string {
	if x != nil {
		if x.xxx_hidden_InboundTransportMode != nil {
			return *x.xxx_hidden_InboundTransportMode
		}
		return ""
	}
	return ""
}

func (x *HOC) GetOutboundTransportMode() string {
	if x != nil {
		if x.xxx_hidden_OutboundTransportMode != nil {
			return *x.xxx_hidden_OutboundTransportMode
		}
		return ""
	}
	return ""
}

func (x *HOC) GetTemperatureControl() string {
	if x != nil {
		if x.xxx_hidden_TemperatureControl != nil {
			return *x.xxx_hidden_TemperatureControl
		}
		return ""
	}
	return ""
}

func (x *HOC) GetCo2EIntensityTtw() string {
	if x != nil {
		if x.xxx_hidden_Co2EIntensityTtw != nil {
			return *x.xxx_hidden_Co2EIntensityTtw
		}
		return ""
	}
	return ""
}

func (x *HOC) GetCo2EIntensityWtw() string {
	if x != nil {
		if x.xxx_hidden_Co2EIntensityWtw != nil {
			return *x.xxx_hidden_Co2EIntensityWtw
		}
		return ""
	}
	return ""
}

func (x *HOC) GetCo2EIntensityThroughput() string {
	if x != nil {
		if x.xxx_hidden_Co2EIntensityThroughput != nil {
			return *x.xxx_hidden_Co2EIntensityThroughput
		}
		return ""
	}
	return ""
}

func (x *HOC) GetEnergyCarriers() []*EnergyCarrier {
	if x != nil {
		if x.xxx_hidden_EnergyCarriers != nil {
			return *x.xxx_hidden_EnergyCarriers
		}
	}
	return nil
}

func (x *HOC) GetIsVerified() bool {
	if x != nil {
		return x.xxx_hidden_IsVerified
	}
	return false
}

func (x *HOC) GetIsAccredited() bool {
	if x != nil {
		return x.xxx_hidden_IsAccredited
	}
	return false
}

func (x *HOC) SetHocId(v string) {
	x.xxx_hidden_HocId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *HOC) SetHubType(v string) {
	x.xxx_hidden_HubType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 12)
}

func (x *HOC) SetHubActivityUnit(v string) {
	x.xxx_hidden_HubActivityUnit = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *HOC) SetInboundTransportMode(v string) {
	x.xxx_hidden_InboundTransportMode = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *HOC) SetOutboundTransportMode(v string) {
	x.xxx_hidden_OutboundTransportMode = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *HOC) SetTemperatureControl(v string) {
	x.xxx_hidden_TemperatureControl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *HOC) SetCo2EIntensityTtw(v string) {
	x.xxx_hidden_Co2EIntensityTtw = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *HOC) SetCo2EIntensityWtw(v string) {
	x.xxx_hidden_Co2EIntensityWtw = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *HOC) SetCo2EIntensityThroughput(v string) {
	x.xxx_hidden_Co2EIntensityThroughput = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *HOC) SetEnergyCarriers(v []*EnergyCarrier) {
	x.xxx_hidden_EnergyCarriers = &v
}

func (x *HOC) SetIsVerified(v bool) {
	x.xxx_hidden_IsVerified = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 12)
}

func (x *HOC) SetIsAccredited(v bool) {
	x.xxx_hidden_IsAccredited = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 12)
}

func (x *HOC) HasHocId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HOC) HasHubType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *HOC) HasHubActivityUnit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HOC) HasInboundTransportMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *HOC) HasOutboundTransportMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *HOC) HasTemperatureControl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *HOC) HasCo2EIntensityTtw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *HOC) HasCo2EIntensityWtw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *HOC) HasCo2EIntensityThroughput() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *HOC) HasIsVerified() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *HOC) HasIsAccredited() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *HOC) ClearHocId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HocId = nil
}

func (x *HOC) ClearHubType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_HubType = nil
}

func (x *HOC) ClearHubActivityUnit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_HubActivityUnit = nil
}

func (x *HOC) ClearInboundTransportMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_InboundTransportMode = nil
}

func (x *HOC) ClearOutboundTransportMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_OutboundTransportMode = nil
}

func (x *HOC) ClearTemperatureControl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_TemperatureControl = nil
}

func (x *HOC) ClearCo2EIntensityTtw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Co2EIntensityTtw = nil
}

func (x *HOC) ClearCo2EIntensityWtw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Co2EIntensityWtw = nil
}

func (x *HOC) ClearCo2EIntensityThroughput() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Co2EIntensityThroughput = nil
}

func (x *HOC) ClearIsVerified() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_IsVerified = false
}

func (x *HOC) ClearIsAccredited() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_IsAccredited = false
}

type HOC_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	HocId                   *string
	HubType                 *string
	HubActivityUnit         *string
	InboundTransportMode    *string
	OutboundTransportMode   *string
	TemperatureControl      *string
	Co2EIntensityTtw        *string
	Co2EIntensityWtw        *string
	Co2EIntensityThroughput *string
	EnergyCarriers          []*EnergyCarrier
	IsVerified              *bool
	IsAccredited            *bool
}

func (b0 HOC_builder) Build() *HOC {
	m0 := &HOC{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HocId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_HocId = b.HocId
	}
	if b.HubType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 12)
		x.xxx_hidden_HubType = b.HubType
	}
	if b.HubActivityUnit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_HubActivityUnit = b.HubActivityUnit
	}
	if b.InboundTransportMode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_InboundTransportMode = b.InboundTransportMode
	}
	if b.OutboundTransportMode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_OutboundTransportMode = b.OutboundTransportMode
	}
	if b.TemperatureControl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_TemperatureControl = b.TemperatureControl
	}
	if b.Co2EIntensityTtw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_Co2EIntensityTtw = b.Co2EIntensityTtw
	}
	if b.Co2EIntensityWtw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_Co2EIntensityWtw = b.Co2EIntensityWtw
	}
	if b.Co2EIntensityThroughput != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_Co2EIntensityThroughput = b.Co2EIntensityThroughput
	}
	x.xxx_hidden_EnergyCarriers = &b.EnergyCarriers
	if b.IsVerified != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 12)
		x.xxx_hidden_IsVerified = *b.IsVerified
	}
	if b.IsAccredited != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 12)
		x.xxx_hidden_IsAccredited = *b.IsAccredited
	}
	return m0
}

var File_wayplatform_connect_ileap_v1_hoc_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_hoc_proto_rawDesc = "" +
	"\n" +
	"&wayplatform/connect/ileap/v1/hoc.proto\x12\x1cwayplatform.connect.ileap.v1\x1a1wayplatform/connect/ileap/v1/energy_carrier.proto\"\xb6\x04\n" +
	"\x03HOC\x12\x15\n" +
	"\x06hoc_id\x18\x01 \x01(\tR\x05hocId\x12\x19\n" +
	"\bhub_type\x18\x02 \x01(\tR\ahubType\x12*\n" +
	"\x11hub_activity_unit\x18\x03 \x01(\tR\x0fhubActivityUnit\x124\n" +
	"\x16inbound_transport_mode\x18\x04 \x01(\tR\x14inboundTransportMode\x126\n" +
	"\x17outbound_transport_mode\x18\x05 \x01(\tR\x15outboundTransportMode\x12/\n" +
	"\x13temperature_control\x18\x06 \x01(\tR\x12temperatureControl\x12,\n" +
	"\x12co2e_intensity_ttw\x18\a \x01(\tR\x10co2eIntensityTTW\x12,\n" +
	"\x12co2e_intensity_wtw\x18\b \x01(\tR\x10co2eIntensityWTW\x12:\n" +
	"\x19co2e_intensity_throughput\x18\t \x01(\tR\x17co2eIntensityThroughput\x12T\n" +
	"\x0fenergy_carriers\x18\n" +
	" \x03(\v2+.wayplatform.connect.ileap.v1.EnergyCarrierR\x0eenergyCarriers\x12\x1f\n" +
	"\vis_verified\x18\v \x01(\bR\n" +
	"isVerified\x12#\n" +
	"\ris_accredited\x18\f \x01(\bR\fisAccreditedB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_hoc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_hoc_proto_goTypes = []any{
	(*HOC)(nil),           // 0: wayplatform.connect.ileap.v1.HOC
	(*EnergyCarrier)(nil), // 1: wayplatform.connect.ileap.v1.EnergyCarrier
}
var file_wayplatform_connect_ileap_v1_hoc_proto_depIdxs = []int32{
	1, // 0: wayplatform.connect.ileap.v1.HOC.energy_carriers:type_name -> wayplatform.connect.ileap.v1.EnergyCarrier
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_hoc_proto_init() }
func file_wayplatform_connect_ileap_v1_hoc_proto_init() {
	if File_wayplatform_connect_ileap_v1_hoc_proto != nil {
		return
	}
	file_wayplatform_connect_ileap_v1_energy_carrier_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_hoc_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_hoc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_hoc_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_hoc_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_hoc_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_hoc_proto = out.File
	file_wayplatform_connect_ileap_v1_hoc_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_hoc_proto_depIdxs = nil
}
