// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/location.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location represents a geographic location.
type Location struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_City        *string                `protobuf:"bytes,1,opt,name=city"`
	xxx_hidden_Country     *string                `protobuf:"bytes,2,opt,name=country"`
	xxx_hidden_Locode      *string                `protobuf:"bytes,3,opt,name=locode"`
	xxx_hidden_Iata        *string                `protobuf:"bytes,4,opt,name=iata"`
	xxx_hidden_Uic         *string                `protobuf:"bytes,5,opt,name=uic"`
	xxx_hidden_Lat         *string                `protobuf:"bytes,6,opt,name=lat"`
	xxx_hidden_Lng         *string                `protobuf:"bytes,7,opt,name=lng"`
	xxx_hidden_Street      *string                `protobuf:"bytes,8,opt,name=street"`
	xxx_hidden_Zip         *string                `protobuf:"bytes,9,opt,name=zip"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_wayplatform_connect_ileap_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Location) GetCity() string {
	if x != nil {
		if x.xxx_hidden_City != nil {
			return *x.xxx_hidden_City
		}
		return ""
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		if x.xxx_hidden_Country != nil {
			return *x.xxx_hidden_Country
		}
		return ""
	}
	return ""
}

func (x *Location) GetLocode() string {
	if x != nil {
		if x.xxx_hidden_Locode != nil {
			return *x.xxx_hidden_Locode
		}
		return ""
	}
	return ""
}

func (x *Location) GetIata() string {
	if x != nil {
		if x.xxx_hidden_Iata != nil {
			return *x.xxx_hidden_Iata
		}
		return ""
	}
	return ""
}

func (x *Location) GetUic() string {
	if x != nil {
		if x.xxx_hidden_Uic != nil {
			return *x.xxx_hidden_Uic
		}
		return ""
	}
	return ""
}

func (x *Location) GetLat() string {
	if x != nil {
		if x.xxx_hidden_Lat != nil {
			return *x.xxx_hidden_Lat
		}
		return ""
	}
	return ""
}

func (x *Location) GetLng() string {
	if x != nil {
		if x.xxx_hidden_Lng != nil {
			return *x.xxx_hidden_Lng
		}
		return ""
	}
	return ""
}

func (x *Location) GetStreet() string {
	if x != nil {
		if x.xxx_hidden_Street != nil {
			return *x.xxx_hidden_Street
		}
		return ""
	}
	return ""
}

func (x *Location) GetZip() string {
	if x != nil {
		if x.xxx_hidden_Zip != nil {
			return *x.xxx_hidden_Zip
		}
		return ""
	}
	return ""
}

func (x *Location) SetCity(v string) {
	x.xxx_hidden_City = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *Location) SetCountry(v string) {
	x.xxx_hidden_Country = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *Location) SetLocode(v string) {
	x.xxx_hidden_Locode = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *Location) SetIata(v string) {
	x.xxx_hidden_Iata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *Location) SetUic(v string) {
	x.xxx_hidden_Uic = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *Location) SetLat(v string) {
	x.xxx_hidden_Lat = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *Location) SetLng(v string) {
	x.xxx_hidden_Lng = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *Location) SetStreet(v string) {
	x.xxx_hidden_Street = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *Location) SetZip(v string) {
	x.xxx_hidden_Zip = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *Location) HasCity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Location) HasCountry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Location) HasLocode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Location) HasIata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Location) HasUic() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Location) HasLat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Location) HasLng() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Location) HasStreet() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Location) HasZip() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Location) ClearCity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_City = nil
}

func (x *Location) ClearCountry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Country = nil
}

func (x *Location) ClearLocode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Locode = nil
}

func (x *Location) ClearIata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Iata = nil
}

func (x *Location) ClearUic() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Uic = nil
}

func (x *Location) ClearLat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Lat = nil
}

func (x *Location) ClearLng() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Lng = nil
}

func (x *Location) ClearStreet() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Street = nil
}

func (x *Location) ClearZip() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Zip = nil
}

type Location_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	City    *string
	Country *string
	Locode  *string
	Iata    *string
	Uic     *string
	Lat     *string
	Lng     *string
	Street  *string
	Zip     *string
}

func (b0 Location_builder) Build() *Location {
	m0 := &Location{}
	b, x := &b0, m0
	_, _ = b, x
	if b.City != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_City = b.City
	}
	if b.Country != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Country = b.Country
	}
	if b.Locode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Locode = b.Locode
	}
	if b.Iata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Iata = b.Iata
	}
	if b.Uic != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Uic = b.Uic
	}
	if b.Lat != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Lat = b.Lat
	}
	if b.Lng != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Lng = b.Lng
	}
	if b.Street != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Street = b.Street
	}
	if b.Zip != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Zip = b.Zip
	}
	return m0
}

var File_wayplatform_connect_ileap_v1_location_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_location_proto_rawDesc = "" +
	"\n" +
	"+wayplatform/connect/ileap/v1/location.proto\x12\x1cwayplatform.connect.ileap.v1\"\xc4\x01\n" +
	"\bLocation\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x16\n" +
	"\x06locode\x18\x03 \x01(\tR\x06locode\x12\x12\n" +
	"\x04iata\x18\x04 \x01(\tR\x04iata\x12\x10\n" +
	"\x03uic\x18\x05 \x01(\tR\x03uic\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\tR\x03lat\x12\x10\n" +
	"\x03lng\x18\a \x01(\tR\x03lng\x12\x16\n" +
	"\x06street\x18\b \x01(\tR\x06street\x12\x10\n" +
	"\x03zip\x18\t \x01(\tR\x03zipB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_location_proto_goTypes = []any{
	(*Location)(nil), // 0: wayplatform.connect.ileap.v1.Location
}
var file_wayplatform_connect_ileap_v1_location_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_location_proto_init() }
func file_wayplatform_connect_ileap_v1_location_proto_init() {
	if File_wayplatform_connect_ileap_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_location_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_location_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_location_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_location_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_location_proto = out.File
	file_wayplatform_connect_ileap_v1_location_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_location_proto_depIdxs = nil
}
