// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/product_footprint.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProductFootprint is the PACT ProductFootprint data type.
type ProductFootprint struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                  *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Comment             *string                `protobuf:"bytes,2,opt,name=comment"`
	xxx_hidden_CompanyIds          []string               `protobuf:"bytes,3,rep,name=company_ids,json=companyIds"`
	xxx_hidden_CompanyName         *string                `protobuf:"bytes,4,opt,name=company_name,json=companyName"`
	xxx_hidden_OrganizationName    *string                `protobuf:"bytes,5,opt,name=organization_name,json=organizationName"`
	xxx_hidden_Created             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created"`
	xxx_hidden_Extensions          *[]*DataModelExtension `protobuf:"bytes,7,rep,name=extensions"`
	xxx_hidden_Pcf                 *CarbonFootprint       `protobuf:"bytes,8,opt,name=pcf"`
	xxx_hidden_PrecedingPfIds      []string               `protobuf:"bytes,9,rep,name=preceding_pf_ids,json=precedingPfIds"`
	xxx_hidden_ProductCategoryCpc  *string                `protobuf:"bytes,10,opt,name=product_category_cpc,json=productCategoryCpc"`
	xxx_hidden_ProductDescription  *string                `protobuf:"bytes,11,opt,name=product_description,json=productDescription"`
	xxx_hidden_ProductIds          []string               `protobuf:"bytes,12,rep,name=product_ids,json=productIds"`
	xxx_hidden_ProductNameCompany  *string                `protobuf:"bytes,13,opt,name=product_name_company,json=productNameCompany"`
	xxx_hidden_SpecVersion         *string                `protobuf:"bytes,14,opt,name=spec_version,json=specVersion"`
	xxx_hidden_Status              *string                `protobuf:"bytes,15,opt,name=status"`
	xxx_hidden_StatusComment       *string                `protobuf:"bytes,16,opt,name=status_comment,json=statusComment"`
	xxx_hidden_Updated             *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated"`
	xxx_hidden_ValidityPeriodEnd   *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=validity_period_end,json=validityPeriodEnd"`
	xxx_hidden_ValidityPeriodStart *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=validity_period_start,json=validityPeriodStart"`
	xxx_hidden_Version             int32                  `protobuf:"varint,20,opt,name=version"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ProductFootprint) Reset() {
	*x = ProductFootprint{}
	mi := &file_wayplatform_connect_ileap_v1_product_footprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductFootprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductFootprint) ProtoMessage() {}

func (x *ProductFootprint) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_product_footprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProductFootprint) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetComment() string {
	if x != nil {
		if x.xxx_hidden_Comment != nil {
			return *x.xxx_hidden_Comment
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetCompanyIds() []string {
	if x != nil {
		return x.xxx_hidden_CompanyIds
	}
	return nil
}

func (x *ProductFootprint) GetCompanyName() string {
	if x != nil {
		if x.xxx_hidden_CompanyName != nil {
			return *x.xxx_hidden_CompanyName
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetOrganizationName() string {
	if x != nil {
		if x.xxx_hidden_OrganizationName != nil {
			return *x.xxx_hidden_OrganizationName
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Created
	}
	return nil
}

func (x *ProductFootprint) GetExtensions() []*DataModelExtension {
	if x != nil {
		if x.xxx_hidden_Extensions != nil {
			return *x.xxx_hidden_Extensions
		}
	}
	return nil
}

func (x *ProductFootprint) GetPcf() *CarbonFootprint {
	if x != nil {
		return x.xxx_hidden_Pcf
	}
	return nil
}

func (x *ProductFootprint) GetPrecedingPfIds() []string {
	if x != nil {
		return x.xxx_hidden_PrecedingPfIds
	}
	return nil
}

func (x *ProductFootprint) GetProductCategoryCpc() string {
	if x != nil {
		if x.xxx_hidden_ProductCategoryCpc != nil {
			return *x.xxx_hidden_ProductCategoryCpc
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetProductDescription() string {
	if x != nil {
		if x.xxx_hidden_ProductDescription != nil {
			return *x.xxx_hidden_ProductDescription
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetProductIds() []string {
	if x != nil {
		return x.xxx_hidden_ProductIds
	}
	return nil
}

func (x *ProductFootprint) GetProductNameCompany() string {
	if x != nil {
		if x.xxx_hidden_ProductNameCompany != nil {
			return *x.xxx_hidden_ProductNameCompany
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetSpecVersion() string {
	if x != nil {
		if x.xxx_hidden_SpecVersion != nil {
			return *x.xxx_hidden_SpecVersion
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetStatusComment() string {
	if x != nil {
		if x.xxx_hidden_StatusComment != nil {
			return *x.xxx_hidden_StatusComment
		}
		return ""
	}
	return ""
}

func (x *ProductFootprint) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Updated
	}
	return nil
}

func (x *ProductFootprint) GetValidityPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ValidityPeriodEnd
	}
	return nil
}

func (x *ProductFootprint) GetValidityPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ValidityPeriodStart
	}
	return nil
}

func (x *ProductFootprint) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *ProductFootprint) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 20)
}

func (x *ProductFootprint) SetComment(v string) {
	x.xxx_hidden_Comment = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 20)
}

func (x *ProductFootprint) SetCompanyIds(v []string) {
	x.xxx_hidden_CompanyIds = v
}

func (x *ProductFootprint) SetCompanyName(v string) {
	x.xxx_hidden_CompanyName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 20)
}

func (x *ProductFootprint) SetOrganizationName(v string) {
	x.xxx_hidden_OrganizationName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 20)
}

func (x *ProductFootprint) SetCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Created = v
}

func (x *ProductFootprint) SetExtensions(v []*DataModelExtension) {
	x.xxx_hidden_Extensions = &v
}

func (x *ProductFootprint) SetPcf(v *CarbonFootprint) {
	x.xxx_hidden_Pcf = v
}

func (x *ProductFootprint) SetPrecedingPfIds(v []string) {
	x.xxx_hidden_PrecedingPfIds = v
}

func (x *ProductFootprint) SetProductCategoryCpc(v string) {
	x.xxx_hidden_ProductCategoryCpc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 20)
}

func (x *ProductFootprint) SetProductDescription(v string) {
	x.xxx_hidden_ProductDescription = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 20)
}

func (x *ProductFootprint) SetProductIds(v []string) {
	x.xxx_hidden_ProductIds = v
}

func (x *ProductFootprint) SetProductNameCompany(v string) {
	x.xxx_hidden_ProductNameCompany = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 20)
}

func (x *ProductFootprint) SetSpecVersion(v string) {
	x.xxx_hidden_SpecVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 20)
}

func (x *ProductFootprint) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 20)
}

func (x *ProductFootprint) SetStatusComment(v string) {
	x.xxx_hidden_StatusComment = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 20)
}

func (x *ProductFootprint) SetUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Updated = v
}

func (x *ProductFootprint) SetValidityPeriodEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_ValidityPeriodEnd = v
}

func (x *ProductFootprint) SetValidityPeriodStart(v *timestamppb.Timestamp) {
	x.xxx_hidden_ValidityPeriodStart = v
}

func (x *ProductFootprint) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 19, 20)
}

func (x *ProductFootprint) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProductFootprint) HasComment() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProductFootprint) HasCompanyName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ProductFootprint) HasOrganizationName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ProductFootprint) HasCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Created != nil
}

func (x *ProductFootprint) HasPcf() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pcf != nil
}

func (x *ProductFootprint) HasProductCategoryCpc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ProductFootprint) HasProductDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *ProductFootprint) HasProductNameCompany() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *ProductFootprint) HasSpecVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *ProductFootprint) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *ProductFootprint) HasStatusComment() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *ProductFootprint) HasUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Updated != nil
}

func (x *ProductFootprint) HasValidityPeriodEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ValidityPeriodEnd != nil
}

func (x *ProductFootprint) HasValidityPeriodStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ValidityPeriodStart != nil
}

func (x *ProductFootprint) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 19)
}

func (x *ProductFootprint) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ProductFootprint) ClearComment() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Comment = nil
}

func (x *ProductFootprint) ClearCompanyName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_CompanyName = nil
}

func (x *ProductFootprint) ClearOrganizationName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_OrganizationName = nil
}

func (x *ProductFootprint) ClearCreated() {
	x.xxx_hidden_Created = nil
}

func (x *ProductFootprint) ClearPcf() {
	x.xxx_hidden_Pcf = nil
}

func (x *ProductFootprint) ClearProductCategoryCpc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_ProductCategoryCpc = nil
}

func (x *ProductFootprint) ClearProductDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_ProductDescription = nil
}

func (x *ProductFootprint) ClearProductNameCompany() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_ProductNameCompany = nil
}

func (x *ProductFootprint) ClearSpecVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_SpecVersion = nil
}

func (x *ProductFootprint) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_Status = nil
}

func (x *ProductFootprint) ClearStatusComment() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_StatusComment = nil
}

func (x *ProductFootprint) ClearUpdated() {
	x.xxx_hidden_Updated = nil
}

func (x *ProductFootprint) ClearValidityPeriodEnd() {
	x.xxx_hidden_ValidityPeriodEnd = nil
}

func (x *ProductFootprint) ClearValidityPeriodStart() {
	x.xxx_hidden_ValidityPeriodStart = nil
}

func (x *ProductFootprint) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 19)
	x.xxx_hidden_Version = 0
}

type ProductFootprint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                  *string
	Comment             *string
	CompanyIds          []string
	CompanyName         *string
	OrganizationName    *string
	Created             *timestamppb.Timestamp
	Extensions          []*DataModelExtension
	Pcf                 *CarbonFootprint
	PrecedingPfIds      []string
	ProductCategoryCpc  *string
	ProductDescription  *string
	ProductIds          []string
	ProductNameCompany  *string
	SpecVersion         *string
	Status              *string
	StatusComment       *string
	Updated             *timestamppb.Timestamp
	ValidityPeriodEnd   *timestamppb.Timestamp
	ValidityPeriodStart *timestamppb.Timestamp
	Version             *int32
}

func (b0 ProductFootprint_builder) Build() *ProductFootprint {
	m0 := &ProductFootprint{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 20)
		x.xxx_hidden_Id = b.Id
	}
	if b.Comment != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 20)
		x.xxx_hidden_Comment = b.Comment
	}
	x.xxx_hidden_CompanyIds = b.CompanyIds
	if b.CompanyName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 20)
		x.xxx_hidden_CompanyName = b.CompanyName
	}
	if b.OrganizationName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 20)
		x.xxx_hidden_OrganizationName = b.OrganizationName
	}
	x.xxx_hidden_Created = b.Created
	x.xxx_hidden_Extensions = &b.Extensions
	x.xxx_hidden_Pcf = b.Pcf
	x.xxx_hidden_PrecedingPfIds = b.PrecedingPfIds
	if b.ProductCategoryCpc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 20)
		x.xxx_hidden_ProductCategoryCpc = b.ProductCategoryCpc
	}
	if b.ProductDescription != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 20)
		x.xxx_hidden_ProductDescription = b.ProductDescription
	}
	x.xxx_hidden_ProductIds = b.ProductIds
	if b.ProductNameCompany != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 20)
		x.xxx_hidden_ProductNameCompany = b.ProductNameCompany
	}
	if b.SpecVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 20)
		x.xxx_hidden_SpecVersion = b.SpecVersion
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 20)
		x.xxx_hidden_Status = b.Status
	}
	if b.StatusComment != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 20)
		x.xxx_hidden_StatusComment = b.StatusComment
	}
	x.xxx_hidden_Updated = b.Updated
	x.xxx_hidden_ValidityPeriodEnd = b.ValidityPeriodEnd
	x.xxx_hidden_ValidityPeriodStart = b.ValidityPeriodStart
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 19, 20)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

var File_wayplatform_connect_ileap_v1_product_footprint_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_product_footprint_proto_rawDesc = "" +
	"\n" +
	"4wayplatform/connect/ileap/v1/product_footprint.proto\x12\x1cwayplatform.connect.ileap.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a3wayplatform/connect/ileap/v1/carbon_footprint.proto\x1a7wayplatform/connect/ileap/v1/data_model_extension.proto\"\xa4\a\n" +
	"\x10ProductFootprint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x1f\n" +
	"\vcompany_ids\x18\x03 \x03(\tR\n" +
	"companyIds\x12!\n" +
	"\fcompany_name\x18\x04 \x01(\tR\vcompanyName\x12+\n" +
	"\x11organization_name\x18\x05 \x01(\tR\x10organizationName\x124\n" +
	"\acreated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12P\n" +
	"\n" +
	"extensions\x18\a \x03(\v20.wayplatform.connect.ileap.v1.DataModelExtensionR\n" +
	"extensions\x12?\n" +
	"\x03pcf\x18\b \x01(\v2-.wayplatform.connect.ileap.v1.CarbonFootprintR\x03pcf\x12(\n" +
	"\x10preceding_pf_ids\x18\t \x03(\tR\x0eprecedingPfIds\x120\n" +
	"\x14product_category_cpc\x18\n" +
	" \x01(\tR\x12productCategoryCpc\x12/\n" +
	"\x13product_description\x18\v \x01(\tR\x12productDescription\x12\x1f\n" +
	"\vproduct_ids\x18\f \x03(\tR\n" +
	"productIds\x120\n" +
	"\x14product_name_company\x18\r \x01(\tR\x12productNameCompany\x12!\n" +
	"\fspec_version\x18\x0e \x01(\tR\vspecVersion\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12%\n" +
	"\x0estatus_comment\x18\x10 \x01(\tR\rstatusComment\x124\n" +
	"\aupdated\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\x12J\n" +
	"\x13validity_period_end\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\x11validityPeriodEnd\x12N\n" +
	"\x15validity_period_start\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\x13validityPeriodStart\x12\x18\n" +
	"\aversion\x18\x14 \x01(\x05R\aversionB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_product_footprint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_product_footprint_proto_goTypes = []any{
	(*ProductFootprint)(nil),      // 0: wayplatform.connect.ileap.v1.ProductFootprint
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*DataModelExtension)(nil),    // 2: wayplatform.connect.ileap.v1.DataModelExtension
	(*CarbonFootprint)(nil),       // 3: wayplatform.connect.ileap.v1.CarbonFootprint
}
var file_wayplatform_connect_ileap_v1_product_footprint_proto_depIdxs = []int32{
	1, // 0: wayplatform.connect.ileap.v1.ProductFootprint.created:type_name -> google.protobuf.Timestamp
	2, // 1: wayplatform.connect.ileap.v1.ProductFootprint.extensions:type_name -> wayplatform.connect.ileap.v1.DataModelExtension
	3, // 2: wayplatform.connect.ileap.v1.ProductFootprint.pcf:type_name -> wayplatform.connect.ileap.v1.CarbonFootprint
	1, // 3: wayplatform.connect.ileap.v1.ProductFootprint.updated:type_name -> google.protobuf.Timestamp
	1, // 4: wayplatform.connect.ileap.v1.ProductFootprint.validity_period_end:type_name -> google.protobuf.Timestamp
	1, // 5: wayplatform.connect.ileap.v1.ProductFootprint.validity_period_start:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_product_footprint_proto_init() }
func file_wayplatform_connect_ileap_v1_product_footprint_proto_init() {
	if File_wayplatform_connect_ileap_v1_product_footprint_proto != nil {
		return
	}
	file_wayplatform_connect_ileap_v1_carbon_footprint_proto_init()
	file_wayplatform_connect_ileap_v1_data_model_extension_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_product_footprint_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_product_footprint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_product_footprint_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_product_footprint_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_product_footprint_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_product_footprint_proto = out.File
	file_wayplatform_connect_ileap_v1_product_footprint_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_product_footprint_proto_depIdxs = nil
}
