// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/shipment_footprint.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShipmentFootprint is the iLEAP extension data for shipment-level footprints.
type ShipmentFootprint struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ShipmentId  *string                `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId"`
	xxx_hidden_Mass        *string                `protobuf:"bytes,2,opt,name=mass"`
	xxx_hidden_Tces        *[]*TCE                `protobuf:"bytes,3,rep,name=tces"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ShipmentFootprint) Reset() {
	*x = ShipmentFootprint{}
	mi := &file_wayplatform_connect_ileap_v1_shipment_footprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentFootprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentFootprint) ProtoMessage() {}

func (x *ShipmentFootprint) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_shipment_footprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShipmentFootprint) GetShipmentId() string {
	if x != nil {
		if x.xxx_hidden_ShipmentId != nil {
			return *x.xxx_hidden_ShipmentId
		}
		return ""
	}
	return ""
}

func (x *ShipmentFootprint) GetMass() string {
	if x != nil {
		if x.xxx_hidden_Mass != nil {
			return *x.xxx_hidden_Mass
		}
		return ""
	}
	return ""
}

func (x *ShipmentFootprint) GetTces() []*TCE {
	if x != nil {
		if x.xxx_hidden_Tces != nil {
			return *x.xxx_hidden_Tces
		}
	}
	return nil
}

func (x *ShipmentFootprint) SetShipmentId(v string) {
	x.xxx_hidden_ShipmentId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ShipmentFootprint) SetMass(v string) {
	x.xxx_hidden_Mass = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ShipmentFootprint) SetTces(v []*TCE) {
	x.xxx_hidden_Tces = &v
}

func (x *ShipmentFootprint) HasShipmentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ShipmentFootprint) HasMass() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ShipmentFootprint) ClearShipmentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ShipmentId = nil
}

func (x *ShipmentFootprint) ClearMass() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Mass = nil
}

type ShipmentFootprint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ShipmentId *string
	Mass       *string
	Tces       []*TCE
}

func (b0 ShipmentFootprint_builder) Build() *ShipmentFootprint {
	m0 := &ShipmentFootprint{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ShipmentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ShipmentId = b.ShipmentId
	}
	if b.Mass != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Mass = b.Mass
	}
	x.xxx_hidden_Tces = &b.Tces
	return m0
}

var File_wayplatform_connect_ileap_v1_shipment_footprint_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_shipment_footprint_proto_rawDesc = "" +
	"\n" +
	"5wayplatform/connect/ileap/v1/shipment_footprint.proto\x12\x1cwayplatform.connect.ileap.v1\x1a&wayplatform/connect/ileap/v1/tce.proto\"\x7f\n" +
	"\x11ShipmentFootprint\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\x12\n" +
	"\x04mass\x18\x02 \x01(\tR\x04mass\x125\n" +
	"\x04tces\x18\x03 \x03(\v2!.wayplatform.connect.ileap.v1.TCER\x04tcesB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_shipment_footprint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_shipment_footprint_proto_goTypes = []any{
	(*ShipmentFootprint)(nil), // 0: wayplatform.connect.ileap.v1.ShipmentFootprint
	(*TCE)(nil),               // 1: wayplatform.connect.ileap.v1.TCE
}
var file_wayplatform_connect_ileap_v1_shipment_footprint_proto_depIdxs = []int32{
	1, // 0: wayplatform.connect.ileap.v1.ShipmentFootprint.tces:type_name -> wayplatform.connect.ileap.v1.TCE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_shipment_footprint_proto_init() }
func file_wayplatform_connect_ileap_v1_shipment_footprint_proto_init() {
	if File_wayplatform_connect_ileap_v1_shipment_footprint_proto != nil {
		return
	}
	file_wayplatform_connect_ileap_v1_tce_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_shipment_footprint_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_shipment_footprint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_shipment_footprint_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_shipment_footprint_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_shipment_footprint_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_shipment_footprint_proto = out.File
	file_wayplatform_connect_ileap_v1_shipment_footprint_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_shipment_footprint_proto_depIdxs = nil
}
