// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/tad.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TAD (Transport Activity Data) is the iLEAP transport activity data type.
type TAD struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ActivityId            *string                `protobuf:"bytes,1,opt,name=activity_id,json=activityId"`
	xxx_hidden_ArrivalAt             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=arrival_at,json=arrivalAt"`
	xxx_hidden_ConsignmentIds        []string               `protobuf:"bytes,3,rep,name=consignment_ids,json=consignmentIds"`
	xxx_hidden_DepartureAt           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=departure_at,json=departureAt"`
	xxx_hidden_Destination           *Location              `protobuf:"bytes,5,opt,name=destination"`
	xxx_hidden_Distance              *GlecDistance          `protobuf:"bytes,6,opt,name=distance"`
	xxx_hidden_EmptyDistanceFactor   *string                `protobuf:"bytes,7,opt,name=empty_distance_factor,json=emptyDistanceFactor"`
	xxx_hidden_EnergyCarriers        *[]*EnergyCarrier      `protobuf:"bytes,8,rep,name=energy_carriers,json=energyCarriers"`
	xxx_hidden_LoadFactor            *string                `protobuf:"bytes,9,opt,name=load_factor,json=loadFactor"`
	xxx_hidden_Mass                  *string                `protobuf:"bytes,10,opt,name=mass"`
	xxx_hidden_Mode                  *string                `protobuf:"bytes,11,opt,name=mode"`
	xxx_hidden_Origin                *Location              `protobuf:"bytes,12,opt,name=origin"`
	xxx_hidden_PackagingOrTrEqAmount uint32                 `protobuf:"varint,13,opt,name=packaging_or_tr_eq_amount,json=packagingOrTrEqAmount"`
	xxx_hidden_PackagingOrTrEqType   *string                `protobuf:"bytes,14,opt,name=packaging_or_tr_eq_type,json=packagingOrTrEqType"`
	xxx_hidden_TemperatureControl    *string                `protobuf:"bytes,15,opt,name=temperature_control,json=temperatureControl"`
	xxx_hidden_Feedstocks            *[]*Feedstock          `protobuf:"bytes,16,rep,name=feedstocks"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *TAD) Reset() {
	*x = TAD{}
	mi := &file_wayplatform_connect_ileap_v1_tad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TAD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAD) ProtoMessage() {}

func (x *TAD) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_tad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TAD) GetActivityId() string {
	if x != nil {
		if x.xxx_hidden_ActivityId != nil {
			return *x.xxx_hidden_ActivityId
		}
		return ""
	}
	return ""
}

func (x *TAD) GetArrivalAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ArrivalAt
	}
	return nil
}

func (x *TAD) GetConsignmentIds() []string {
	if x != nil {
		return x.xxx_hidden_ConsignmentIds
	}
	return nil
}

func (x *TAD) GetDepartureAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DepartureAt
	}
	return nil
}

func (x *TAD) GetDestination() *Location {
	if x != nil {
		return x.xxx_hidden_Destination
	}
	return nil
}

func (x *TAD) GetDistance() *GlecDistance {
	if x != nil {
		return x.xxx_hidden_Distance
	}
	return nil
}

func (x *TAD) GetEmptyDistanceFactor() string {
	if x != nil {
		if x.xxx_hidden_EmptyDistanceFactor != nil {
			return *x.xxx_hidden_EmptyDistanceFactor
		}
		return ""
	}
	return ""
}

func (x *TAD) GetEnergyCarriers() []*EnergyCarrier {
	if x != nil {
		if x.xxx_hidden_EnergyCarriers != nil {
			return *x.xxx_hidden_EnergyCarriers
		}
	}
	return nil
}

func (x *TAD) GetLoadFactor() string {
	if x != nil {
		if x.xxx_hidden_LoadFactor != nil {
			return *x.xxx_hidden_LoadFactor
		}
		return ""
	}
	return ""
}

func (x *TAD) GetMass() string {
	if x != nil {
		if x.xxx_hidden_Mass != nil {
			return *x.xxx_hidden_Mass
		}
		return ""
	}
	return ""
}

func (x *TAD) GetMode() string {
	if x != nil {
		if x.xxx_hidden_Mode != nil {
			return *x.xxx_hidden_Mode
		}
		return ""
	}
	return ""
}

func (x *TAD) GetOrigin() *Location {
	if x != nil {
		return x.xxx_hidden_Origin
	}
	return nil
}

func (x *TAD) GetPackagingOrTrEqAmount() uint32 {
	if x != nil {
		return x.xxx_hidden_PackagingOrTrEqAmount
	}
	return 0
}

func (x *TAD) GetPackagingOrTrEqType() string {
	if x != nil {
		if x.xxx_hidden_PackagingOrTrEqType != nil {
			return *x.xxx_hidden_PackagingOrTrEqType
		}
		return ""
	}
	return ""
}

func (x *TAD) GetTemperatureControl() string {
	if x != nil {
		if x.xxx_hidden_TemperatureControl != nil {
			return *x.xxx_hidden_TemperatureControl
		}
		return ""
	}
	return ""
}

func (x *TAD) GetFeedstocks() []*Feedstock {
	if x != nil {
		if x.xxx_hidden_Feedstocks != nil {
			return *x.xxx_hidden_Feedstocks
		}
	}
	return nil
}

func (x *TAD) SetActivityId(v string) {
	x.xxx_hidden_ActivityId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 16)
}

func (x *TAD) SetArrivalAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ArrivalAt = v
}

func (x *TAD) SetConsignmentIds(v []string) {
	x.xxx_hidden_ConsignmentIds = v
}

func (x *TAD) SetDepartureAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DepartureAt = v
}

func (x *TAD) SetDestination(v *Location) {
	x.xxx_hidden_Destination = v
}

func (x *TAD) SetDistance(v *GlecDistance) {
	x.xxx_hidden_Distance = v
}

func (x *TAD) SetEmptyDistanceFactor(v string) {
	x.xxx_hidden_EmptyDistanceFactor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 16)
}

func (x *TAD) SetEnergyCarriers(v []*EnergyCarrier) {
	x.xxx_hidden_EnergyCarriers = &v
}

func (x *TAD) SetLoadFactor(v string) {
	x.xxx_hidden_LoadFactor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 16)
}

func (x *TAD) SetMass(v string) {
	x.xxx_hidden_Mass = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 16)
}

func (x *TAD) SetMode(v string) {
	x.xxx_hidden_Mode = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 16)
}

func (x *TAD) SetOrigin(v *Location) {
	x.xxx_hidden_Origin = v
}

func (x *TAD) SetPackagingOrTrEqAmount(v uint32) {
	x.xxx_hidden_PackagingOrTrEqAmount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 16)
}

func (x *TAD) SetPackagingOrTrEqType(v string) {
	x.xxx_hidden_PackagingOrTrEqType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 16)
}

func (x *TAD) SetTemperatureControl(v string) {
	x.xxx_hidden_TemperatureControl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 16)
}

func (x *TAD) SetFeedstocks(v []*Feedstock) {
	x.xxx_hidden_Feedstocks = &v
}

func (x *TAD) HasActivityId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TAD) HasArrivalAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ArrivalAt != nil
}

func (x *TAD) HasDepartureAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DepartureAt != nil
}

func (x *TAD) HasDestination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Destination != nil
}

func (x *TAD) HasDistance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Distance != nil
}

func (x *TAD) HasEmptyDistanceFactor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *TAD) HasLoadFactor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *TAD) HasMass() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *TAD) HasMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *TAD) HasOrigin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Origin != nil
}

func (x *TAD) HasPackagingOrTrEqAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *TAD) HasPackagingOrTrEqType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *TAD) HasTemperatureControl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *TAD) ClearActivityId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ActivityId = nil
}

func (x *TAD) ClearArrivalAt() {
	x.xxx_hidden_ArrivalAt = nil
}

func (x *TAD) ClearDepartureAt() {
	x.xxx_hidden_DepartureAt = nil
}

func (x *TAD) ClearDestination() {
	x.xxx_hidden_Destination = nil
}

func (x *TAD) ClearDistance() {
	x.xxx_hidden_Distance = nil
}

func (x *TAD) ClearEmptyDistanceFactor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_EmptyDistanceFactor = nil
}

func (x *TAD) ClearLoadFactor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_LoadFactor = nil
}

func (x *TAD) ClearMass() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Mass = nil
}

func (x *TAD) ClearMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Mode = nil
}

func (x *TAD) ClearOrigin() {
	x.xxx_hidden_Origin = nil
}

func (x *TAD) ClearPackagingOrTrEqAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_PackagingOrTrEqAmount = 0
}

func (x *TAD) ClearPackagingOrTrEqType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_PackagingOrTrEqType = nil
}

func (x *TAD) ClearTemperatureControl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_TemperatureControl = nil
}

type TAD_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActivityId            *string
	ArrivalAt             *timestamppb.Timestamp
	ConsignmentIds        []string
	DepartureAt           *timestamppb.Timestamp
	Destination           *Location
	Distance              *GlecDistance
	EmptyDistanceFactor   *string
	EnergyCarriers        []*EnergyCarrier
	LoadFactor            *string
	Mass                  *string
	Mode                  *string
	Origin                *Location
	PackagingOrTrEqAmount *uint32
	PackagingOrTrEqType   *string
	TemperatureControl    *string
	Feedstocks            []*Feedstock
}

func (b0 TAD_builder) Build() *TAD {
	m0 := &TAD{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ActivityId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 16)
		x.xxx_hidden_ActivityId = b.ActivityId
	}
	x.xxx_hidden_ArrivalAt = b.ArrivalAt
	x.xxx_hidden_ConsignmentIds = b.ConsignmentIds
	x.xxx_hidden_DepartureAt = b.DepartureAt
	x.xxx_hidden_Destination = b.Destination
	x.xxx_hidden_Distance = b.Distance
	if b.EmptyDistanceFactor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 16)
		x.xxx_hidden_EmptyDistanceFactor = b.EmptyDistanceFactor
	}
	x.xxx_hidden_EnergyCarriers = &b.EnergyCarriers
	if b.LoadFactor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 16)
		x.xxx_hidden_LoadFactor = b.LoadFactor
	}
	if b.Mass != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 16)
		x.xxx_hidden_Mass = b.Mass
	}
	if b.Mode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 16)
		x.xxx_hidden_Mode = b.Mode
	}
	x.xxx_hidden_Origin = b.Origin
	if b.PackagingOrTrEqAmount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 16)
		x.xxx_hidden_PackagingOrTrEqAmount = *b.PackagingOrTrEqAmount
	}
	if b.PackagingOrTrEqType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 16)
		x.xxx_hidden_PackagingOrTrEqType = b.PackagingOrTrEqType
	}
	if b.TemperatureControl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 16)
		x.xxx_hidden_TemperatureControl = b.TemperatureControl
	}
	x.xxx_hidden_Feedstocks = &b.Feedstocks
	return m0
}

var File_wayplatform_connect_ileap_v1_tad_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_tad_proto_rawDesc = "" +
	"\n" +
	"&wayplatform/connect/ileap/v1/tad.proto\x12\x1cwayplatform.connect.ileap.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a0wayplatform/connect/ileap/v1/glec_distance.proto\x1a+wayplatform/connect/ileap/v1/location.proto\x1a,wayplatform/connect/ileap/v1/feedstock.proto\x1a1wayplatform/connect/ileap/v1/energy_carrier.proto\"\xd8\x06\n" +
	"\x03TAD\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x129\n" +
	"\n" +
	"arrival_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tarrivalAt\x12'\n" +
	"\x0fconsignment_ids\x18\x03 \x03(\tR\x0econsignmentIds\x12=\n" +
	"\fdeparture_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vdepartureAt\x12H\n" +
	"\vdestination\x18\x05 \x01(\v2&.wayplatform.connect.ileap.v1.LocationR\vdestination\x12F\n" +
	"\bdistance\x18\x06 \x01(\v2*.wayplatform.connect.ileap.v1.GlecDistanceR\bdistance\x122\n" +
	"\x15empty_distance_factor\x18\a \x01(\tR\x13emptyDistanceFactor\x12T\n" +
	"\x0fenergy_carriers\x18\b \x03(\v2+.wayplatform.connect.ileap.v1.EnergyCarrierR\x0eenergyCarriers\x12\x1f\n" +
	"\vload_factor\x18\t \x01(\tR\n" +
	"loadFactor\x12\x12\n" +
	"\x04mass\x18\n" +
	" \x01(\tR\x04mass\x12\x12\n" +
	"\x04mode\x18\v \x01(\tR\x04mode\x12>\n" +
	"\x06origin\x18\f \x01(\v2&.wayplatform.connect.ileap.v1.LocationR\x06origin\x128\n" +
	"\x19packaging_or_tr_eq_amount\x18\r \x01(\rR\x15packagingOrTrEqAmount\x124\n" +
	"\x17packaging_or_tr_eq_type\x18\x0e \x01(\tR\x13packagingOrTrEqType\x12/\n" +
	"\x13temperature_control\x18\x0f \x01(\tR\x12temperatureControl\x12G\n" +
	"\n" +
	"feedstocks\x18\x10 \x03(\v2'.wayplatform.connect.ileap.v1.FeedstockR\n" +
	"feedstocksB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_tad_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_tad_proto_goTypes = []any{
	(*TAD)(nil),                   // 0: wayplatform.connect.ileap.v1.TAD
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*Location)(nil),              // 2: wayplatform.connect.ileap.v1.Location
	(*GlecDistance)(nil),          // 3: wayplatform.connect.ileap.v1.GlecDistance
	(*EnergyCarrier)(nil),         // 4: wayplatform.connect.ileap.v1.EnergyCarrier
	(*Feedstock)(nil),             // 5: wayplatform.connect.ileap.v1.Feedstock
}
var file_wayplatform_connect_ileap_v1_tad_proto_depIdxs = []int32{
	1, // 0: wayplatform.connect.ileap.v1.TAD.arrival_at:type_name -> google.protobuf.Timestamp
	1, // 1: wayplatform.connect.ileap.v1.TAD.departure_at:type_name -> google.protobuf.Timestamp
	2, // 2: wayplatform.connect.ileap.v1.TAD.destination:type_name -> wayplatform.connect.ileap.v1.Location
	3, // 3: wayplatform.connect.ileap.v1.TAD.distance:type_name -> wayplatform.connect.ileap.v1.GlecDistance
	4, // 4: wayplatform.connect.ileap.v1.TAD.energy_carriers:type_name -> wayplatform.connect.ileap.v1.EnergyCarrier
	2, // 5: wayplatform.connect.ileap.v1.TAD.origin:type_name -> wayplatform.connect.ileap.v1.Location
	5, // 6: wayplatform.connect.ileap.v1.TAD.feedstocks:type_name -> wayplatform.connect.ileap.v1.Feedstock
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_tad_proto_init() }
func file_wayplatform_connect_ileap_v1_tad_proto_init() {
	if File_wayplatform_connect_ileap_v1_tad_proto != nil {
		return
	}
	file_wayplatform_connect_ileap_v1_glec_distance_proto_init()
	file_wayplatform_connect_ileap_v1_location_proto_init()
	file_wayplatform_connect_ileap_v1_feedstock_proto_init()
	file_wayplatform_connect_ileap_v1_energy_carrier_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_tad_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_tad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_tad_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_tad_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_tad_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_tad_proto = out.File
	file_wayplatform_connect_ileap_v1_tad_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_tad_proto_depIdxs = nil
}
