// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/tce.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TCE (Transport Chain Element) represents a single leg in a shipment.
type TCE struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TceId             *string                `protobuf:"bytes,1,opt,name=tce_id,json=tceId"`
	xxx_hidden_TocId             *string                `protobuf:"bytes,2,opt,name=toc_id,json=tocId"`
	xxx_hidden_HocId             *string                `protobuf:"bytes,3,opt,name=hoc_id,json=hocId"`
	xxx_hidden_ShipmentId        *string                `protobuf:"bytes,4,opt,name=shipment_id,json=shipmentId"`
	xxx_hidden_Co2ETtw           *string                `protobuf:"bytes,5,opt,name=co2e_ttw,json=co2eTTW"`
	xxx_hidden_Co2EWtw           *string                `protobuf:"bytes,6,opt,name=co2e_wtw,json=co2eWTW"`
	xxx_hidden_Mass              *string                `protobuf:"bytes,7,opt,name=mass"`
	xxx_hidden_TransportActivity *string                `protobuf:"bytes,8,opt,name=transport_activity,json=transportActivity"`
	xxx_hidden_Distance          *GlecDistance          `protobuf:"bytes,9,opt,name=distance"`
	xxx_hidden_PrevTceIds        []string               `protobuf:"bytes,10,rep,name=prev_tce_ids,json=prevTceIds"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *TCE) Reset() {
	*x = TCE{}
	mi := &file_wayplatform_connect_ileap_v1_tce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCE) ProtoMessage() {}

func (x *TCE) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_tce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TCE) GetTceId() string {
	if x != nil {
		if x.xxx_hidden_TceId != nil {
			return *x.xxx_hidden_TceId
		}
		return ""
	}
	return ""
}

func (x *TCE) GetTocId() string {
	if x != nil {
		if x.xxx_hidden_TocId != nil {
			return *x.xxx_hidden_TocId
		}
		return ""
	}
	return ""
}

func (x *TCE) GetHocId() string {
	if x != nil {
		if x.xxx_hidden_HocId != nil {
			return *x.xxx_hidden_HocId
		}
		return ""
	}
	return ""
}

func (x *TCE) GetShipmentId() string {
	if x != nil {
		if x.xxx_hidden_ShipmentId != nil {
			return *x.xxx_hidden_ShipmentId
		}
		return ""
	}
	return ""
}

func (x *TCE) GetCo2ETtw() string {
	if x != nil {
		if x.xxx_hidden_Co2ETtw != nil {
			return *x.xxx_hidden_Co2ETtw
		}
		return ""
	}
	return ""
}

func (x *TCE) GetCo2EWtw() string {
	if x != nil {
		if x.xxx_hidden_Co2EWtw != nil {
			return *x.xxx_hidden_Co2EWtw
		}
		return ""
	}
	return ""
}

func (x *TCE) GetMass() string {
	if x != nil {
		if x.xxx_hidden_Mass != nil {
			return *x.xxx_hidden_Mass
		}
		return ""
	}
	return ""
}

func (x *TCE) GetTransportActivity() string {
	if x != nil {
		if x.xxx_hidden_TransportActivity != nil {
			return *x.xxx_hidden_TransportActivity
		}
		return ""
	}
	return ""
}

func (x *TCE) GetDistance() *GlecDistance {
	if x != nil {
		return x.xxx_hidden_Distance
	}
	return nil
}

func (x *TCE) GetPrevTceIds() []string {
	if x != nil {
		return x.xxx_hidden_PrevTceIds
	}
	return nil
}

func (x *TCE) SetTceId(v string) {
	x.xxx_hidden_TceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *TCE) SetTocId(v string) {
	x.xxx_hidden_TocId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *TCE) SetHocId(v string) {
	x.xxx_hidden_HocId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *TCE) SetShipmentId(v string) {
	x.xxx_hidden_ShipmentId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *TCE) SetCo2ETtw(v string) {
	x.xxx_hidden_Co2ETtw = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *TCE) SetCo2EWtw(v string) {
	x.xxx_hidden_Co2EWtw = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *TCE) SetMass(v string) {
	x.xxx_hidden_Mass = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *TCE) SetTransportActivity(v string) {
	x.xxx_hidden_TransportActivity = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *TCE) SetDistance(v *GlecDistance) {
	x.xxx_hidden_Distance = v
}

func (x *TCE) SetPrevTceIds(v []string) {
	x.xxx_hidden_PrevTceIds = v
}

func (x *TCE) HasTceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TCE) HasTocId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TCE) HasHocId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TCE) HasShipmentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TCE) HasCo2ETtw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TCE) HasCo2EWtw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *TCE) HasMass() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *TCE) HasTransportActivity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *TCE) HasDistance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Distance != nil
}

func (x *TCE) ClearTceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TceId = nil
}

func (x *TCE) ClearTocId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TocId = nil
}

func (x *TCE) ClearHocId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_HocId = nil
}

func (x *TCE) ClearShipmentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ShipmentId = nil
}

func (x *TCE) ClearCo2ETtw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Co2ETtw = nil
}

func (x *TCE) ClearCo2EWtw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Co2EWtw = nil
}

func (x *TCE) ClearMass() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Mass = nil
}

func (x *TCE) ClearTransportActivity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_TransportActivity = nil
}

func (x *TCE) ClearDistance() {
	x.xxx_hidden_Distance = nil
}

type TCE_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TceId             *string
	TocId             *string
	HocId             *string
	ShipmentId        *string
	Co2ETtw           *string
	Co2EWtw           *string
	Mass              *string
	TransportActivity *string
	Distance          *GlecDistance
	PrevTceIds        []string
}

func (b0 TCE_builder) Build() *TCE {
	m0 := &TCE{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_TceId = b.TceId
	}
	if b.TocId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_TocId = b.TocId
	}
	if b.HocId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_HocId = b.HocId
	}
	if b.ShipmentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_ShipmentId = b.ShipmentId
	}
	if b.Co2ETtw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_Co2ETtw = b.Co2ETtw
	}
	if b.Co2EWtw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_Co2EWtw = b.Co2EWtw
	}
	if b.Mass != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_Mass = b.Mass
	}
	if b.TransportActivity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_TransportActivity = b.TransportActivity
	}
	x.xxx_hidden_Distance = b.Distance
	x.xxx_hidden_PrevTceIds = b.PrevTceIds
	return m0
}

var File_wayplatform_connect_ileap_v1_tce_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_tce_proto_rawDesc = "" +
	"\n" +
	"&wayplatform/connect/ileap/v1/tce.proto\x12\x1cwayplatform.connect.ileap.v1\x1a0wayplatform/connect/ileap/v1/glec_distance.proto\"\xce\x02\n" +
	"\x03TCE\x12\x15\n" +
	"\x06tce_id\x18\x01 \x01(\tR\x05tceId\x12\x15\n" +
	"\x06toc_id\x18\x02 \x01(\tR\x05tocId\x12\x15\n" +
	"\x06hoc_id\x18\x03 \x01(\tR\x05hocId\x12\x1f\n" +
	"\vshipment_id\x18\x04 \x01(\tR\n" +
	"shipmentId\x12\x19\n" +
	"\bco2e_ttw\x18\x05 \x01(\tR\aco2eTTW\x12\x19\n" +
	"\bco2e_wtw\x18\x06 \x01(\tR\aco2eWTW\x12\x12\n" +
	"\x04mass\x18\a \x01(\tR\x04mass\x12-\n" +
	"\x12transport_activity\x18\b \x01(\tR\x11transportActivity\x12F\n" +
	"\bdistance\x18\t \x01(\v2*.wayplatform.connect.ileap.v1.GlecDistanceR\bdistance\x12 \n" +
	"\fprev_tce_ids\x18\n" +
	" \x03(\tR\n" +
	"prevTceIdsB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_tce_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_tce_proto_goTypes = []any{
	(*TCE)(nil),          // 0: wayplatform.connect.ileap.v1.TCE
	(*GlecDistance)(nil), // 1: wayplatform.connect.ileap.v1.GlecDistance
}
var file_wayplatform_connect_ileap_v1_tce_proto_depIdxs = []int32{
	1, // 0: wayplatform.connect.ileap.v1.TCE.distance:type_name -> wayplatform.connect.ileap.v1.GlecDistance
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_tce_proto_init() }
func file_wayplatform_connect_ileap_v1_tce_proto_init() {
	if File_wayplatform_connect_ileap_v1_tce_proto != nil {
		return
	}
	file_wayplatform_connect_ileap_v1_glec_distance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_tce_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_tce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_tce_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_tce_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_tce_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_tce_proto = out.File
	file_wayplatform_connect_ileap_v1_tce_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_tce_proto_depIdxs = nil
}
