// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wayplatform/connect/ileap/v1/toc.proto

package ileapv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TOC (Transport Operation Category) is the iLEAP extension for transport operation footprints.
type TOC struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TocId                   *string                `protobuf:"bytes,1,opt,name=toc_id,json=tocId"`
	xxx_hidden_Mode                    *string                `protobuf:"bytes,2,opt,name=mode"`
	xxx_hidden_TemperatureControl      *string                `protobuf:"bytes,3,opt,name=temperature_control,json=temperatureControl"`
	xxx_hidden_Co2EIntensityTtw        *string                `protobuf:"bytes,4,opt,name=co2e_intensity_ttw,json=co2eIntensityTTW"`
	xxx_hidden_Co2EIntensityWtw        *string                `protobuf:"bytes,5,opt,name=co2e_intensity_wtw,json=co2eIntensityWTW"`
	xxx_hidden_Co2EIntensityThroughput *string                `protobuf:"bytes,6,opt,name=co2e_intensity_throughput,json=co2eIntensityThroughput"`
	xxx_hidden_EnergyCarriers          *[]*EnergyCarrier      `protobuf:"bytes,7,rep,name=energy_carriers,json=energyCarriers"`
	xxx_hidden_LoadFactor              *string                `protobuf:"bytes,8,opt,name=load_factor,json=loadFactor"`
	xxx_hidden_EmptyDistanceFactor     *string                `protobuf:"bytes,9,opt,name=empty_distance_factor,json=emptyDistanceFactor"`
	xxx_hidden_TransportActivityUnit   *string                `protobuf:"bytes,10,opt,name=transport_activity_unit,json=transportActivityUnit"`
	xxx_hidden_TruckLoadingSequence    *string                `protobuf:"bytes,11,opt,name=truck_loading_sequence,json=truckLoadingSequence"`
	xxx_hidden_IsVerified              bool                   `protobuf:"varint,12,opt,name=is_verified,json=isVerified"`
	xxx_hidden_IsAccredited            bool                   `protobuf:"varint,13,opt,name=is_accredited,json=isAccredited"`
	XXX_raceDetectHookData             protoimpl.RaceDetectHookData
	XXX_presence                       [1]uint32
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *TOC) Reset() {
	*x = TOC{}
	mi := &file_wayplatform_connect_ileap_v1_toc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOC) ProtoMessage() {}

func (x *TOC) ProtoReflect() protoreflect.Message {
	mi := &file_wayplatform_connect_ileap_v1_toc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TOC) GetTocId() string {
	if x != nil {
		if x.xxx_hidden_TocId != nil {
			return *x.xxx_hidden_TocId
		}
		return ""
	}
	return ""
}

func (x *TOC) GetMode() string {
	if x != nil {
		if x.xxx_hidden_Mode != nil {
			return *x.xxx_hidden_Mode
		}
		return ""
	}
	return ""
}

func (x *TOC) GetTemperatureControl() string {
	if x != nil {
		if x.xxx_hidden_TemperatureControl != nil {
			return *x.xxx_hidden_TemperatureControl
		}
		return ""
	}
	return ""
}

func (x *TOC) GetCo2EIntensityTtw() string {
	if x != nil {
		if x.xxx_hidden_Co2EIntensityTtw != nil {
			return *x.xxx_hidden_Co2EIntensityTtw
		}
		return ""
	}
	return ""
}

func (x *TOC) GetCo2EIntensityWtw() string {
	if x != nil {
		if x.xxx_hidden_Co2EIntensityWtw != nil {
			return *x.xxx_hidden_Co2EIntensityWtw
		}
		return ""
	}
	return ""
}

func (x *TOC) GetCo2EIntensityThroughput() string {
	if x != nil {
		if x.xxx_hidden_Co2EIntensityThroughput != nil {
			return *x.xxx_hidden_Co2EIntensityThroughput
		}
		return ""
	}
	return ""
}

func (x *TOC) GetEnergyCarriers() []*EnergyCarrier {
	if x != nil {
		if x.xxx_hidden_EnergyCarriers != nil {
			return *x.xxx_hidden_EnergyCarriers
		}
	}
	return nil
}

func (x *TOC) GetLoadFactor() string {
	if x != nil {
		if x.xxx_hidden_LoadFactor != nil {
			return *x.xxx_hidden_LoadFactor
		}
		return ""
	}
	return ""
}

func (x *TOC) GetEmptyDistanceFactor() string {
	if x != nil {
		if x.xxx_hidden_EmptyDistanceFactor != nil {
			return *x.xxx_hidden_EmptyDistanceFactor
		}
		return ""
	}
	return ""
}

func (x *TOC) GetTransportActivityUnit() string {
	if x != nil {
		if x.xxx_hidden_TransportActivityUnit != nil {
			return *x.xxx_hidden_TransportActivityUnit
		}
		return ""
	}
	return ""
}

func (x *TOC) GetTruckLoadingSequence() string {
	if x != nil {
		if x.xxx_hidden_TruckLoadingSequence != nil {
			return *x.xxx_hidden_TruckLoadingSequence
		}
		return ""
	}
	return ""
}

func (x *TOC) GetIsVerified() bool {
	if x != nil {
		return x.xxx_hidden_IsVerified
	}
	return false
}

func (x *TOC) GetIsAccredited() bool {
	if x != nil {
		return x.xxx_hidden_IsAccredited
	}
	return false
}

func (x *TOC) SetTocId(v string) {
	x.xxx_hidden_TocId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 13)
}

func (x *TOC) SetMode(v string) {
	x.xxx_hidden_Mode = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 13)
}

func (x *TOC) SetTemperatureControl(v string) {
	x.xxx_hidden_TemperatureControl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 13)
}

func (x *TOC) SetCo2EIntensityTtw(v string) {
	x.xxx_hidden_Co2EIntensityTtw = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 13)
}

func (x *TOC) SetCo2EIntensityWtw(v string) {
	x.xxx_hidden_Co2EIntensityWtw = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 13)
}

func (x *TOC) SetCo2EIntensityThroughput(v string) {
	x.xxx_hidden_Co2EIntensityThroughput = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 13)
}

func (x *TOC) SetEnergyCarriers(v []*EnergyCarrier) {
	x.xxx_hidden_EnergyCarriers = &v
}

func (x *TOC) SetLoadFactor(v string) {
	x.xxx_hidden_LoadFactor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 13)
}

func (x *TOC) SetEmptyDistanceFactor(v string) {
	x.xxx_hidden_EmptyDistanceFactor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 13)
}

func (x *TOC) SetTransportActivityUnit(v string) {
	x.xxx_hidden_TransportActivityUnit = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 13)
}

func (x *TOC) SetTruckLoadingSequence(v string) {
	x.xxx_hidden_TruckLoadingSequence = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 13)
}

func (x *TOC) SetIsVerified(v bool) {
	x.xxx_hidden_IsVerified = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 13)
}

func (x *TOC) SetIsAccredited(v bool) {
	x.xxx_hidden_IsAccredited = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 13)
}

func (x *TOC) HasTocId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TOC) HasMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TOC) HasTemperatureControl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TOC) HasCo2EIntensityTtw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TOC) HasCo2EIntensityWtw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TOC) HasCo2EIntensityThroughput() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *TOC) HasLoadFactor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *TOC) HasEmptyDistanceFactor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *TOC) HasTransportActivityUnit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *TOC) HasTruckLoadingSequence() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *TOC) HasIsVerified() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *TOC) HasIsAccredited() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *TOC) ClearTocId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TocId = nil
}

func (x *TOC) ClearMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Mode = nil
}

func (x *TOC) ClearTemperatureControl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_TemperatureControl = nil
}

func (x *TOC) ClearCo2EIntensityTtw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Co2EIntensityTtw = nil
}

func (x *TOC) ClearCo2EIntensityWtw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Co2EIntensityWtw = nil
}

func (x *TOC) ClearCo2EIntensityThroughput() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Co2EIntensityThroughput = nil
}

func (x *TOC) ClearLoadFactor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_LoadFactor = nil
}

func (x *TOC) ClearEmptyDistanceFactor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_EmptyDistanceFactor = nil
}

func (x *TOC) ClearTransportActivityUnit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_TransportActivityUnit = nil
}

func (x *TOC) ClearTruckLoadingSequence() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_TruckLoadingSequence = nil
}

func (x *TOC) ClearIsVerified() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_IsVerified = false
}

func (x *TOC) ClearIsAccredited() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_IsAccredited = false
}

type TOC_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TocId                   *string
	Mode                    *string
	TemperatureControl      *string
	Co2EIntensityTtw        *string
	Co2EIntensityWtw        *string
	Co2EIntensityThroughput *string
	EnergyCarriers          []*EnergyCarrier
	LoadFactor              *string
	EmptyDistanceFactor     *string
	TransportActivityUnit   *string
	TruckLoadingSequence    *string
	IsVerified              *bool
	IsAccredited            *bool
}

func (b0 TOC_builder) Build() *TOC {
	m0 := &TOC{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TocId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 13)
		x.xxx_hidden_TocId = b.TocId
	}
	if b.Mode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 13)
		x.xxx_hidden_Mode = b.Mode
	}
	if b.TemperatureControl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 13)
		x.xxx_hidden_TemperatureControl = b.TemperatureControl
	}
	if b.Co2EIntensityTtw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 13)
		x.xxx_hidden_Co2EIntensityTtw = b.Co2EIntensityTtw
	}
	if b.Co2EIntensityWtw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 13)
		x.xxx_hidden_Co2EIntensityWtw = b.Co2EIntensityWtw
	}
	if b.Co2EIntensityThroughput != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 13)
		x.xxx_hidden_Co2EIntensityThroughput = b.Co2EIntensityThroughput
	}
	x.xxx_hidden_EnergyCarriers = &b.EnergyCarriers
	if b.LoadFactor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 13)
		x.xxx_hidden_LoadFactor = b.LoadFactor
	}
	if b.EmptyDistanceFactor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 13)
		x.xxx_hidden_EmptyDistanceFactor = b.EmptyDistanceFactor
	}
	if b.TransportActivityUnit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 13)
		x.xxx_hidden_TransportActivityUnit = b.TransportActivityUnit
	}
	if b.TruckLoadingSequence != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 13)
		x.xxx_hidden_TruckLoadingSequence = b.TruckLoadingSequence
	}
	if b.IsVerified != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 13)
		x.xxx_hidden_IsVerified = *b.IsVerified
	}
	if b.IsAccredited != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 13)
		x.xxx_hidden_IsAccredited = *b.IsAccredited
	}
	return m0
}

var File_wayplatform_connect_ileap_v1_toc_proto protoreflect.FileDescriptor

const file_wayplatform_connect_ileap_v1_toc_proto_rawDesc = "" +
	"\n" +
	"&wayplatform/connect/ileap/v1/toc.proto\x12\x1cwayplatform.connect.ileap.v1\x1a1wayplatform/connect/ileap/v1/energy_carrier.proto\"\xd8\x04\n" +
	"\x03TOC\x12\x15\n" +
	"\x06toc_id\x18\x01 \x01(\tR\x05tocId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12/\n" +
	"\x13temperature_control\x18\x03 \x01(\tR\x12temperatureControl\x12,\n" +
	"\x12co2e_intensity_ttw\x18\x04 \x01(\tR\x10co2eIntensityTTW\x12,\n" +
	"\x12co2e_intensity_wtw\x18\x05 \x01(\tR\x10co2eIntensityWTW\x12:\n" +
	"\x19co2e_intensity_throughput\x18\x06 \x01(\tR\x17co2eIntensityThroughput\x12T\n" +
	"\x0fenergy_carriers\x18\a \x03(\v2+.wayplatform.connect.ileap.v1.EnergyCarrierR\x0eenergyCarriers\x12\x1f\n" +
	"\vload_factor\x18\b \x01(\tR\n" +
	"loadFactor\x122\n" +
	"\x15empty_distance_factor\x18\t \x01(\tR\x13emptyDistanceFactor\x126\n" +
	"\x17transport_activity_unit\x18\n" +
	" \x01(\tR\x15transportActivityUnit\x124\n" +
	"\x16truck_loading_sequence\x18\v \x01(\tR\x14truckLoadingSequence\x12\x1f\n" +
	"\vis_verified\x18\f \x01(\bR\n" +
	"isVerified\x12#\n" +
	"\ris_accredited\x18\r \x01(\bR\fisAccreditedB,Z*github.com/way-platform/ileap-go/ileapv1pbb\beditionsp\xe8\a"

var file_wayplatform_connect_ileap_v1_toc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wayplatform_connect_ileap_v1_toc_proto_goTypes = []any{
	(*TOC)(nil),           // 0: wayplatform.connect.ileap.v1.TOC
	(*EnergyCarrier)(nil), // 1: wayplatform.connect.ileap.v1.EnergyCarrier
}
var file_wayplatform_connect_ileap_v1_toc_proto_depIdxs = []int32{
	1, // 0: wayplatform.connect.ileap.v1.TOC.energy_carriers:type_name -> wayplatform.connect.ileap.v1.EnergyCarrier
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wayplatform_connect_ileap_v1_toc_proto_init() }
func file_wayplatform_connect_ileap_v1_toc_proto_init() {
	if File_wayplatform_connect_ileap_v1_toc_proto != nil {
		return
	}
	file_wayplatform_connect_ileap_v1_energy_carrier_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wayplatform_connect_ileap_v1_toc_proto_rawDesc), len(file_wayplatform_connect_ileap_v1_toc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wayplatform_connect_ileap_v1_toc_proto_goTypes,
		DependencyIndexes: file_wayplatform_connect_ileap_v1_toc_proto_depIdxs,
		MessageInfos:      file_wayplatform_connect_ileap_v1_toc_proto_msgTypes,
	}.Build()
	File_wayplatform_connect_ileap_v1_toc_proto = out.File
	file_wayplatform_connect_ileap_v1_toc_proto_goTypes = nil
	file_wayplatform_connect_ileap_v1_toc_proto_depIdxs = nil
}
