apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ileap-demo-server
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
      - image: europe-north1-docker.pkg.dev/way-ileap-demo-prod/ghcr/way-platform/ileap-go/ileap@sha256:a784d523dc235704c693025b2d54c6733aa31c94bc50505e083b593a2352fd08
        args:
        - demo-server
        ports:
        - containerPort: 8080
