apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ileap-demo-server
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: europe-north1-docker.pkg.dev/way-ileap-demo-prod/ghcr/way-platform/ileap-go/ileap@sha256:b69f1e49d3d9c7da959fc0580754a6590f6ae8d5f7893e5313ca4dc85b68a1d4
          args:
            - demo-server
          ports:
            - containerPort: 8080
