apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ileap-demo-server
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
      - image: europe-north1-docker.pkg.dev/way-ileap-demo-prod/ghcr/way-platform/ileap-go/ileap@sha256:90d447238d95fccf83012174fa84be41c1b3b4f93fdb83cc9e41d8692114a74d
        args:
        - demo-server
        ports:
        - containerPort: 8080
