Output cli.gif

Set FontSize 16
Set Width 1200
Set Height 600
Set BorderRadius 10
Set WindowBar Colorful

Type "ileap"
Sleep 250ms
Enter
Sleep 3s
Ctrl+L

Type "ileap auth login --base-url https://ileap.wayplatform.com --client-id hello --client-secret pathfinder"
Sleep 250ms
Enter
Sleep 2s
Ctrl+L

Type "ileap footprints"
Sleep 1s
Enter
Sleep 2s
Ctrl+L

Type "ileap tad"
Sleep 1s
Enter
Sleep 2s
Ctrl+L

Type "ileap auth logout"
Sleep 250ms
Enter
Sleep 2s
